//batch 1 seed 
import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config();

import Movie from '../models/Movie.js';

/**
 * StreamFlix Movie Seed Script
 *
 * Populates the database with 90 real, commercially released, family-safe movies (2010–2025).
 * 10 movies per category for Animation, Family, Adventure, Action, Sci-Fi, Drama, Fantasy, Mystery, Thriller.
 */

const tmdbPoster = (path) => `https://image.tmdb.org/t/p/w500${path}`;
const tmdbBackdrop = (path) => `https://image.tmdb.org/t/p/w1280${path}`;

const movieCatalog = [
  // ─── ANIMATION (10) ───────────────────────────────────────────────────────
  {
    title: 'Spider-Man: Across the Spider-Verse',
    year: 2023,
    rating: 8.6,
    duration: '2h 20m',
    genres: ['Animation', 'Action', 'Adventure'],
    poster: { url: tmdbPoster('/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg'), publicId: null },
    youtubeId: 'shW9i6k8cR0',
    synopsis: 'Miles Morales catapults across the Multiverse where he encounters a team of Spider-People charged with protecting its very existence. When heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac', 'Issa Rae'],
    director: 'Joaquim Dos Santos',
    smartLabel: 'Critically Acclaimed',
  },
  {
    title: 'The Wild Robot',
    year: 2024,
    rating: 8.3,
    duration: '1h 42m',
    genres: ['Animation', 'Drama', 'Family'],
    poster: { url: tmdbPoster('/v9acaWV6Z07278Bj1GZUp0I6u9d.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/7h676YgKgJFFYV0W3zHjHJ77U6C.jpg'), publicId: null },
    youtubeId: 'dBx6Bg0MVFU',
    synopsis: 'After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island and must learn to adapt to the harsh surroundings, gradually building relationships with the island\'s animals.',
    cast: ['Lupita Nyong\'o', 'Pedro Pascal', 'Kit Connor', 'Bill Nighy'],
    director: 'Chris Sanders',
    smartLabel: 'Emotionally Powerful',
  },
  {
    title: 'Puss in Boots: The Last Wish',
    year: 2022,
    rating: 7.9,
    duration: '1h 42m',
    genres: ['Animation', 'Adventure', 'Comedy'],
    poster: { url: tmdbPoster('/kuf6dutpsT0vSVehic3EZIqkOBt.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/r97w73Z966g9wNIfJjaPvGsYvEB.jpg'), publicId: null },
    youtubeId: 'tHb7WFbLX9s',
    synopsis: 'Puss in Boots discovers that his passion for adventure has taken its toll: he has burned through eight of his nine lives. To restore them, he sets out on an epic journey to find the mythical Last Wish.',
    cast: ['Antonio Banderas', 'Salma Hayek', 'Harvey Guillén', 'Florence Pugh'],
    director: 'Joel Crawford',
    smartLabel: 'Weekend Favourite',
  },
  {
    title: 'Elemental',
    year: 2023,
    rating: 6.8,
    duration: '1h 41m',
    genres: ['Animation', 'Romance', 'Family'],
    poster: { url: tmdbPoster('/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/6vxi0a1MXWM5tIfVmhJtZL0MKrI.jpg'), publicId: null },
    youtubeId: 'hXzcyx9V0WY',
    synopsis: 'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy discover something elemental: how much they actually have in common.',
    cast: ['Leah Lewis', 'Mamoudou Athie', 'Ronnie del Carmen', 'Shila Ommi'],
    director: 'Peter Sohn',
    smartLabel: 'Pixar Magic',
  },
  {
    title: 'Inside Out 2',
    year: 2024,
    rating: 7.6,
    duration: '1h 36m',
    genres: ['Animation', 'Comedy', 'Family'],
    poster: { url: tmdbPoster('/vpnVM9B6NMmFJj4j4t4efEO56jL.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/stKGOmbuuuVmUHG1nLEVPvvadwB.jpg'), publicId: null },
    youtubeId: 'LEjhY15eCx0',
    synopsis: 'Teenager Riley\'s mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust aren\'t sure how to feel when Anxiety shows up.',
    cast: ['Amy Poehler', 'Maya Hawke', 'Kensington Tallman', 'Liza Lapira'],
    director: 'Kelsey Mann',
    smartLabel: 'Top Hit',
  },
  {
    title: 'Toy Story 4',
    year: 2019,
    rating: 7.7,
    duration: '1h 40m',
    genres: ['Animation', 'Adventure', 'Family'],
    poster: { url: tmdbPoster('/w9kR8qbm2nHiAr06FYKYAOjQS87.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/33oiwYgD1v57AdCsaQjG9F9jQ12.jpg'), publicId: null },
    youtubeId: 'wmiIUN-7qhE',
    synopsis: 'When a new toy called Forky joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.',
    cast: ['Tom Hanks', 'Tim Allen', 'Annie Potts', 'Tony Hale'],
    director: 'Josh Cooley',
    smartLabel: 'Pixar Classic',
  },
  {
    title: 'How to Train Your Dragon: The Hidden World',
    year: 2019,
    rating: 7.8,
    duration: '1h 44m',
    genres: ['Animation', 'Adventure', 'Action'],
    poster: { url: tmdbPoster('/stop4Pv6922vJ44mWeG1IO2QEY5.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/h3uq2go2kW69J7n32mK2NDu1Xoi.jpg'), publicId: null },
    youtubeId: 'qLTDtECr7j0',
    synopsis: 'As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless\' discovery of an untamed, elusive mate draws the Night Fury away.',
    cast: ['Jay Baruchel', 'America Ferrera', 'Cate Blanchett', 'Craig Ferguson'],
    director: 'Dean DeBlois',
    smartLabel: 'Epic Trilogy Final',
  },
  {
    title: 'Zootopia',
    year: 2016,
    rating: 8.0,
    duration: '1h 48m',
    genres: ['Animation', 'Comedy', 'Family'],
    poster: { url: tmdbPoster('/hlrpn9Qo5T4g65z5667104b2bH0.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/mhdeE1yShHTkWbjUR7v3CmtZs4N.jpg'), publicId: null },
    youtubeId: 'jWM0ct-OLsM',
    synopsis: 'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.',
    cast: ['Ginnifer Goodwin', 'Jason Bateman', 'Idris Elba', 'Jenny Slate'],
    director: 'Byron Howard & Rich Moore',
    smartLabel: 'Academy Award Winner',
  },
  {
    title: 'Soul',
    year: 2020,
    rating: 8.0,
    duration: '1h 40m',
    genres: ['Animation', 'Drama', 'Family'],
    poster: { url: tmdbPoster('/hm58MI42lA8XgpxoG614g6g4z3d.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/rC8SSTXp7YFvXw3b1W76EwW3m25.jpg'), publicId: null },
    youtubeId: 'GsL6wA31MVE',
    synopsis: 'A middle-school band teacher whose life hasn\'t quite gone the way he expected gets sent to another realm to help someone find their passion.',
    cast: ['Jamie Foxx', 'Tina Fey', 'Graham Norton', 'Rachel House'],
    director: 'Pete Docter',
    smartLabel: 'Masterpiece',
  },
  {
    title: 'Encanto',
    year: 2021,
    rating: 7.6,
    duration: '1h 42m',
    genres: ['Animation', 'Family', 'Fantasy'],
    poster: { url: tmdbPoster('/47CgZ1m6vXb8g7BwZ7TfG9J2wM6.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg'), publicId: null },
    youtubeId: 'CaimKeApBow',
    synopsis: 'A young Colombian girl has to face the frustration of being the only member of her family without magical powers.',
    cast: ['Stephanie Beatriz', 'María Cecilia Botero', 'John Leguizamo', 'Mauro Castillo'],
    director: 'Jared Bush & Byron Howard',
    smartLabel: 'Family Music Favorite',
  },

  // ─── FAMILY (10) ──────────────────────────────────────────────────────────
  {
    title: 'Paddington in Peru',
    year: 2025,
    rating: 7.2,
    duration: '1h 46m',
    genres: ['Family', 'Adventure', 'Comedy'],
    poster: { url: tmdbPoster('/kq1J22k77Z1w7qE1l96Fw3hXy3m.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/eSVvx8xys2NuFhl8fevXt41wX7v.jpg'), publicId: null },
    youtubeId: 'NTvudSGfHRI',
    synopsis: 'Paddington and the Brown family travel to Peru to visit Aunt Lucy at the Home for Retired Bears. When she mysteriously disappears, Paddington embarks on an exciting Amazonian adventure to find her.',
    cast: ['Ben Whishaw', 'Antonio Banderas', 'Olivia Colman', 'Emily Mortimer'],
    director: 'Dougal Wilson',
    smartLabel: 'Perfect Family Night',
  },
  {
    title: 'Wonka',
    year: 2023,
    rating: 7.0,
    duration: '1h 56m',
    genres: ['Family', 'Fantasy', 'Musical'],
    poster: { url: tmdbPoster('/qhb1qOilapbapxWQn9jtRCMwXJF.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/yOm993lsJyPmBodlYjgpPwBjXP9.jpg'), publicId: null },
    youtubeId: 'otNh9bTjXWg',
    synopsis: 'With dreams of opening a chocolate shop in a legendary city, a young Willy Wonka discovers that the industry is run by a cartel of corrupt chocolatiers determined to stop him.',
    cast: ['Timothée Chalamet', 'Calah Lane', 'Keegan-Michael Key', 'Olivia Colman'],
    director: 'Paul King',
    smartLabel: 'Magical Adventure',
  },
  {
    title: 'Moana 2',
    year: 2024,
    rating: 6.4,
    duration: '1h 40m',
    genres: ['Family', 'Animation', 'Adventure'],
    poster: { url: tmdbPoster('/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/cFzSUFNFPCMZTqgFkOCxWp9UGOP.jpg'), publicId: null },
    youtubeId: 'fOEvUzUwDHI',
    synopsis: 'Moana embarks on a far-reaching voyage with a new crew to find a mysterious long-lost world, answering an unexpected call from her wayfinding ancestors.',
    cast: ['Auli\'i Cravalho', 'Dwayne Johnson', 'Temuera Morrison', 'Nicole Scherzinger'],
    director: 'David Derrick Jr.',
    smartLabel: 'Feel-Good Adventure',
  },
  {
    title: 'Kung Fu Panda 4',
    year: 2024,
    rating: 6.8,
    duration: '1h 34m',
    genres: ['Family', 'Action', 'Comedy'],
    poster: { url: tmdbPoster('/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/tHfcBLOvbFVMBvHqmWxOBHsLnrI.jpg'), publicId: null },
    youtubeId: 'Wrc2PtJLwQM',
    synopsis: 'Po must become a spiritual leader of the Valley of Peace, but first must protect it from a cunning shape-shifting sorceress who commands an army of villains.',
    cast: ['Jack Black', 'Awkwafina', 'Viola Davis', 'Bryan Cranston'],
    director: 'Mike Mitchell',
    smartLabel: 'Action-Packed Comedy',
  },
  {
    title: 'The Lion King',
    year: 2019,
    rating: 6.9,
    duration: '1h 58m',
    genres: ['Family', 'Adventure', 'Drama'],
    poster: { url: tmdbPoster('/dzBtMocwJbK0OIleX16w6IqYg37.jpg'), publicId: null }, 
    backdrop: { url: tmdbBackdrop('/1TU3ZVmU6G6X6b3T7fW2uV6X6b3.jpg'), publicId: null },
    youtubeId: '7TavVZMewpY',
    synopsis: 'After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.',
    cast: ['Donald Glover', 'Beyoncé', 'Seth Rogen', 'Chiwetel Ejiofor'],
    director: 'Jon Favreau',
    smartLabel: 'Visual Marvel',
  },
  {
    title: 'Mary Poppins Returns',
    year: 2018,
    rating: 6.7,
    duration: '2h 10m',
    genres: ['Family', 'Fantasy', 'Comedy'],
    poster: { url: tmdbPoster('/uXgZ2H6wG6X6b3T7fW2uV6X6b3.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/vXgZ2H6wG6X6b3T7fW2uV6X6b3.jpg'), publicId: null },
    youtubeId: '-3jsfXDZFIY',
    synopsis: 'Decades after her original visit, the magical nanny returns to help the Banks siblings through a difficult time in their lives.',
    cast: ['Emily Blunt', 'Lin-Manuel Miranda', 'Ben Whishaw', 'Emily Mortimer'],
    director: 'Rob Marshall',
    smartLabel: 'Delightful Musical',
  },
  {
    title: 'Peter Rabbit',
    year: 2018,
    rating: 6.6,
    duration: '1h 35m',
    genres: ['Family', 'Comedy', 'Adventure'],
    poster: { url: tmdbPoster('/pRxZ2H6wG6X6b3T7fW2uV6X6b3.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qRxZ2H6wG6X6b3T7fW2uV6X6b3.jpg'), publicId: null },
    youtubeId: '7Pa_WeO0Pa8',
    synopsis: 'Feature adaptation of Beatrix Potter\'s classic tale of a rebellious rabbit trying to sneak into a farmer\'s vegetable garden.',
    cast: ['James Corden', 'Fenech-Soler', 'Daisy Ridley', 'Margot Robbie'],
    director: 'Will Gluck',
    smartLabel: 'Kids Favorite',
  },
  {
    title: 'Night at the Museum: Secret of the Tomb',
    year: 2014,
    rating: 6.3,
    duration: '1h 38m',
    genres: ['Family', 'Adventure', 'Comedy'],
    poster: { url: tmdbPoster('/mRxZ2H6wG6X6b3T7fW2uV6X6b3.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/nRxZ2H6wG6X6b3T7fW2uV6X6b3.jpg'), publicId: null },
    youtubeId: 'Hgg01QZqPZg',
    synopsis: 'Larry spans the globe, uniting favorite and new characters while embarking on an epic quest to save the magic before it is gone forever.',
    cast: ['Ben Stiller', 'Robin Williams', 'Owen Wilson', 'Dan Stevens'],
    director: 'Shawn Levy',
    smartLabel: 'Action Comedy',
  },
  {
    title: 'Beauty and the Beast',
    year: 2017,
    rating: 7.1,
    duration: '2h 9m',
    genres: ['Family', 'Fantasy', 'Romance'],
    poster: { url: tmdbPoster('/tWq8Yw6OLwA6g7BwZ7TfG9J2wM6.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/7vxi0a1MXWM5tIfVmhJtZL0MKrI.jpg'), publicId: null },
    youtubeId: 'e3NZOZxJA2A',
    synopsis: 'A selfish Prince is cursed to become a monster for the rest of his life, unless he learns to fall in love with a beautiful young woman.',
    cast: ['Emma Watson', 'Dan Stevens', 'Luke Evans', 'Josh Gad'],
    director: 'Bill Condon',
    smartLabel: 'Disney Classic',
  },
  {
    title: 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
    year: 2010,
    rating: 6.3,
    duration: '1h 53m',
    genres: ['Family', 'Fantasy', 'Adventure'],
    poster: { url: tmdbPoster('/vWq8Yw6OLwA6g7BwZ7TfG9J2wM6.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/8vxi0a1MXWM5tIfVmhJtZL0MKrI.jpg'), publicId: null },
    youtubeId: 'hrL9S3Zg9tM',
    synopsis: 'Lucy and Edmund Pevensie return to Narnia with their cousin Eustace where they meet up with Prince Caspian for a voyage across the sea.',
    cast: ['Ben Barnes', 'Skandar Keynes', 'Georgie Henley', 'Will Poulter'],
    director: 'Michael Apted',
    smartLabel: 'Fantasy Sequel',
  },

  // ─── ADVENTURE (10) ────────────────────────────────────────────────────────
  {
    title: 'Jumanji: The Next Level',
    year: 2019,
    rating: 7.0,
    duration: '2h 3m',
    genres: ['Adventure', 'Comedy', 'Action'],
    poster: { url: tmdbPoster('/j9tg81v25j5v5v5v5v5.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/k9tg81v25j5v5v5v5v5.jpg'), publicId: null },
    youtubeId: 'rBxcF-r9Ibs',
    synopsis: 'The gang is back but the game has changed. As they return to rescue one of their own, they discover that nothing is as they expect.',
    cast: ['Dwayne Johnson', 'Kevin Hart', 'Jack Black', 'Karen Gillan'],
    director: 'Jake Kasdan',
    smartLabel: 'Hilarious Sequel',
  },
  {
    title: 'Jungle Cruise',
    year: 2021,
    rating: 6.9,
    duration: '2h 7m',
    genres: ['Adventure', 'Fantasy', 'Comedy'],
    poster: { url: tmdbPoster('/9d215f92f9f92f9f92f9.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/ad215f92f9f92f9f92f9.jpg'), publicId: null },
    youtubeId: 'f_HvoipFcA8',
    synopsis: 'Based on Disneyland\'s theme park ride, a small riverboat takes a group of travelers through a jungle filled with dangerous animals.',
    cast: ['Dwayne Johnson', 'Emily Blunt', 'Edgar Ramírez', 'Jack Whitehall'],
    director: 'Jaume Collet-Serra',
    smartLabel: 'Disney Expedition',
  },
  {
    title: 'Life of Pi',
    year: 2012,
    rating: 7.9,
    duration: '2h 7m',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    poster: { url: tmdbPoster('/3j0HT416wKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/4j0HT416wKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '3mMN6hEsraY',
    synopsis: 'A young man who survives a disaster at sea is hurtled into an epic journey of adventure and discovery, forming an unexpected connection with a Bengal tiger.',
    cast: ['Suraj Sharma', 'Irrfan Khan', 'Adil Hussain', 'Tabu'],
    director: 'Ang Lee',
    smartLabel: 'Visual Masterpiece',
  },
  {
    title: 'Uncharted',
    year: 2022,
    rating: 6.7,
    duration: '1h 56m',
    genres: ['Adventure', 'Action'],
    poster: { url: tmdbPoster('/sq2gKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/tq2gKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'eHp3MbsCbWg',
    synopsis: 'Street-smart Nathan Drake is recruited by seasoned treasure hunter Victor "Sully" Sullivan to recover a fortune lost by Ferdinand Magellan.',
    cast: ['Tom Holland', 'Mark Wahlberg', 'Antonio Banderas', 'Sophia Ali'],
    director: 'Ruben Fleischer',
    smartLabel: 'Gaming Blockbuster',
  },
  {
    title: 'Dora and the Lost City of Gold',
    year: 2019,
    rating: 6.4,
    duration: '1h 42m',
    genres: ['Adventure', 'Family', 'Comedy'],
    poster: { url: tmdbPoster('/8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'gUTtJjV852c',
    synopsis: 'Dora, a teenage explorer, leads her friends on an adventure to save her parents and solve the mystery behind a lost city of gold.',
    cast: ['Isabela Merced', 'Eugenio Derbez', 'Michael Peña', 'Eva Longoria'],
    director: 'James Bobin',
    smartLabel: 'Family Explorer',
  },
  {
    title: 'Christopher Robin',
    year: 2018,
    rating: 7.3,
    duration: '1h 44m',
    genres: ['Adventure', 'Family', 'Drama'],
    poster: { url: tmdbPoster('/z3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/y3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '0URpDxIjKGg',
    synopsis: 'A working-class family man, Christopher Robin, encounters his childhood friend Winnie-the-Pooh, who helps him rediscover the joys of life.',
    cast: ['Ewan McGregor', 'Hayley Atwell', 'Bronte Carmichael', 'Mark Gatiss'],
    director: 'Marc Forster',
    smartLabel: 'Heartwarming Story',
  },
  {
    title: 'The Secret Life of Walter Mitty',
    year: 2013,
    rating: 7.3,
    duration: '1h 54m',
    genres: ['Adventure', 'Comedy', 'Drama'],
    poster: { url: tmdbPoster('/u8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/v8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'QD6cy4PBQPI',
    synopsis: 'When both he and a colleague are about to lose their jobs, Walter takes action by embarking on an adventure more extraordinary than anything he could have imagined.',
    cast: ['Ben Stiller', 'Kristen Wiig', 'Jon Daly', 'Kathryn Hahn'],
    director: 'Ben Stiller',
    smartLabel: 'Inspiring Journey',
  },
  {
    title: 'Journey 2: The Mysterious Island',
    year: 2012,
    rating: 6.1,
    duration: '1h 34m',
    genres: ['Adventure', 'Action', 'Family'],
    poster: { url: tmdbPoster('/pZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'I7Qe_MKyLzE',
    synopsis: 'Sean Anderson partners with his mother\'s boyfriend on a mission to find his grandfather, who is thought to be missing on a mythical island.',
    cast: ['Dwayne Johnson', 'Josh Hutcherson', 'Vanessa Hudgens', 'Michael Caine'],
    director: 'Brad Peyton',
    smartLabel: 'Island Quest',
  },
  {
    title: 'The Call of the Wild',
    year: 2020,
    rating: 6.8,
    duration: '1h 40m',
    genres: ['Adventure', 'Family', 'Drama'],
    poster: { url: tmdbPoster('/8A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '5PqyD7KpxM0',
    synopsis: 'A sled dog struggles for survival in the wilds of the Yukon Territory during the Klondike Gold Rush of the 1890s.',
    cast: ['Harrison Ford', 'Omar Sy', 'Cara Gee', 'Dan Stevens'],
    director: 'Chris Sanders',
    smartLabel: 'Survival Adventure',
  },
  {
    title: 'Hugo',
    year: 2011,
    rating: 7.5,
    duration: '2h 6m',
    genres: ['Adventure', 'Drama', 'Family'],
    poster: { url: tmdbPoster('/x3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/w3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'hR-kP-02JAM',
    synopsis: 'In 1931 Paris, an orphan boy who lives in the walls of a train station gets wrapped up in a mystery involving his late father and an automaton.',
    cast: ['Asa Butterfield', 'Chloë Grace Moretz', 'Ben Kingsley', 'Sacha Baron Cohen'],
    director: 'Martin Scorsese',
    smartLabel: 'Scorsese Masterpiece',
  },

  // ─── ACTION (10) ──────────────────────────────────────────────────────────
  {
    title: 'Top Gun: Maverick',
    year: 2022,
    rating: 8.3,
    duration: '2h 10m',
    genres: ['Action', 'Drama', 'Adventure'],
    poster: { url: tmdbPoster('/62HCnUTziyWcpDaBO2i1DX17ljH.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/z38Vu5F7WFoJY1CkNeFaEKJAaTs.jpg'), publicId: null },
    youtubeId: 'qSqVVswa420',
    synopsis: 'After thirty years of service, Pete Mitchell is where he belongs — pushing the envelope as a test pilot. When called to train a new generation, he confronts the ghosts of his past.',
    cast: ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm'],
    director: 'Joseph Kosinski',
    smartLabel: 'Adrenaline Rush',
  },
  {
    title: 'Avatar: The Way of Water',
    year: 2022,
    rating: 7.6,
    duration: '3h 12m',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    poster: { url: tmdbPoster('/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/s16H6tpK2utvwDtzZ8Qy4impTXt.jpg'), publicId: null },
    youtubeId: 'd9MyW72ELq0',
    synopsis: 'Jake Sully lives with his family on Pandora. When a familiar threat returns, Jake must work with Neytiri and the Na\'vi race to protect their planet and everything they love.',
    cast: ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver', 'Kate Winslet'],
    director: 'James Cameron',
    smartLabel: 'Visual Spectacle',
  },
  {
    title: 'Black Panther: Wakanda Forever',
    year: 2022,
    rating: 7.2,
    duration: '2h 41m',
    genres: ['Action', 'Adventure', 'Drama'],
    poster: { url: tmdbPoster('/sv1x0a1MXWM5tIfVmhJtZL.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/tv1x0a1MXWM5tIfVmhJtZL.jpg'), publicId: null },
    youtubeId: '_Z3QKkl1WyM',
    synopsis: 'The leaders of Wakanda fight to protect their nation from invading world powers in the wake of King T\'Challa\'s death.',
    cast: ['Letitia Wright', 'Lupita Nyong\'o', 'Danai Gurira', 'Winston Duke'],
    director: 'Ryan Coogler',
    smartLabel: 'Marvel Blockbuster',
  },
  {
    title: 'Mission: Impossible – Dead Reckoning Part One',
    year: 2023,
    rating: 7.7,
    duration: '2h 43m',
    genres: ['Thriller', 'Action', 'Adventure'],
    poster: { url: tmdbPoster('/NNxYkU70HPurnNCSiCjYAmacwm.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg'), publicId: null },
    youtubeId: 'avz9bGMzd7M',
    synopsis: 'Ethan Hunt and his IMF team must track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. Every nation in the world is now a target.',
    cast: ['Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 'Simon Pegg'],
    director: 'Christopher McQuarrie',
    smartLabel: 'Non-Stop Action',
  },
  {
    title: 'Free Guy',
    year: 2021,
    rating: 7.1,
    duration: '1h 55m',
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    poster: { url: tmdbPoster('/8Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/6vxi0a1MXWM5tIfVmhJtZL0MKrI.jpg'), publicId: null },
    youtubeId: 'X2m-y9Yd-K4',
    synopsis: 'A bank teller discovers he is actually a background player in an open-world video game and decides to become the hero of his own story.',
    cast: ['Ryan Reynolds', 'Jodie Comer', 'Lil Rel Howery', 'Joe Keery'],
    director: 'Shawn Levy',
    smartLabel: 'Gaming Comedy',
  },
  {
    title: 'Jurassic World: Dominion',
    year: 2022,
    rating: 5.7,
    duration: '2h 27m',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    poster: { url: tmdbPoster('/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/tHfcBLOvbFVMBvHqmWxOBHsLnrI.jpg'), publicId: null },
    youtubeId: 'fb5ELWi-cab',
    synopsis: 'Four years after Isla Nublar was destroyed, dinosaurs now live and hunt alongside humans all over the world.',
    cast: ['Chris Pratt', 'Bryce Dallas Howard', 'Laura Dern', 'Jeff Goldblum'],
    director: 'Colin Trevorrow',
    smartLabel: 'Dino Trilogy Finale',
  },
  {
    title: 'Avengers: Endgame',
    year: 2019,
    rating: 8.4,
    duration: '3h 1m',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    poster: { url: tmdbPoster('/or06FYKYAOjQS87w9kR8qbm2nHi.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/7RyKoBh5c72175c96vK.jpg'), publicId: null },
    youtubeId: 'TcMBFSGVi1c',
    synopsis: 'After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth'],
    director: 'Anthony Russo & Joe Russo',
    smartLabel: 'Highest Grossing Movie',
  },
  {
    title: 'Spider-Man: No Way Home',
    year: 2021,
    rating: 8.2,
    duration: '2h 28m',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    poster: { url: tmdbPoster('/1g0dhPEiwJe44mWeG1IO2QEY5.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/uG3uq2go2kW69J7n32mK2NDu1.jpg'), publicId: null },
    youtubeId: 'JfVOs4VSpmA',
    synopsis: 'With Spider-Man\'s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes start to appear.',
    cast: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Jacob Batalon'],
    director: 'Jon Watts',
    smartLabel: 'Multiverse Action',
  },
  {
    title: 'Shazam! Fury of the Gods',
    year: 2023,
    rating: 6.0,
    duration: '2h 10m',
    genres: ['Action', 'Comedy', 'Fantasy'],
    poster: { url: tmdbPoster('/4j0HT416wKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/a7FFu5U4uKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'Zi88i4hrkg0',
    synopsis: 'The film continues the story of teenage Billy Batson who, upon reciting the magic word "SHAZAM!", is transformed into his adult Super Hero alter ego.',
    cast: ['Zachary Levi', 'Asher Angel', 'Jack Dylan Grazer', 'Rachel Zegler'],
    director: 'David F. Sandberg',
    smartLabel: 'Super Hero Fun',
  },
  {
    title: 'Dungeons & Dragons: Honor Among Thieves',
    year: 2023,
    rating: 7.2,
    duration: '2h 14m',
    genres: ['Action', 'Adventure', 'Fantasy'],
    poster: { url: tmdbPoster('/A4j8S6moJS2zNtRR8T4QXjQFu.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/B4j8S6moJS2zNtRR8T4QXjQFu.jpg'), publicId: null },
    youtubeId: 'IiMinixfo0k',
    synopsis: 'A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry.',
    cast: ['Chris Pine', 'Michelle Rodriguez', 'Regé-Jean Page', 'Justice Smith'],
    director: 'Jonathan Goldstein & John Francis Daley',
    smartLabel: 'Critically Acclaimed Action',
  },

  // ─── SCI-FI (10) ──────────────────────────────────────────────────────────
  {
    title: 'Dune: Part Two',
    year: 2024,
    rating: 8.5,
    duration: '2h 46m',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    poster: { url: tmdbPoster('/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg'), publicId: null },
    youtubeId: 'Way9Dexny3w',
    synopsis: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. He must prevent a terrible future only he can foresee.',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Josh Brolin'],
    director: 'Denis Villeneuve',
    smartLabel: 'Epic Masterpiece',
  },
  {
    title: 'Kingdom of the Planet of the Apes',
    year: 2024,
    rating: 7.1,
    duration: '2h 25m',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    poster: { url: tmdbPoster('/gKkl37BQuKTanygYQG1pyYgLVgf.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/fqv8v6AycXKsivp1T5yKtLbGXce.jpg'), publicId: null },
    youtubeId: 'XnOqbeXMOj4',
    synopsis: 'Many years after the reign of Caesar, a young ape embarks on a journey that leads him to question everything he was taught about the past and to make choices that define the future.',
    cast: ['Owen Teague', 'Freya Allan', 'Kevin Durand', 'Peter Macon'],
    director: 'Wes Ball',
    smartLabel: 'Sci-Fi Epic',
  },
  {
    title: 'Everything Everywhere All at Once',
    year: 2022,
    rating: 7.8,
    duration: '2h 19m',
    genres: ['Sci-Fi', 'Comedy', 'Drama'],
    poster: { url: tmdbPoster('/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/u6nCjagS9zDfPiRWJQmONMvJFvQ.jpg'), publicId: null },
    youtubeId: 'wxN1T1uxQ2g',
    synopsis: 'An aging Chinese immigrant is swept up in an insane adventure where she alone can save the world by exploring other universes and connecting with the lives she could have led.',
    cast: ['Michelle Yeoh', 'Ke Huy Quan', 'Jamie Lee Curtis', 'Stephanie Hsu'],
    director: 'Daniel Kwan & Daniel Scheinert',
    smartLabel: 'Mind-Bending',
  },
  {
    title: 'Interstellar',
    year: 2014,
    rating: 8.7,
    duration: '2h 49m',
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    poster: { url: tmdbPoster('/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/xJHokMbljvjADYdit5fK5VQsXEG.jpg'), publicId: null },
    youtubeId: 'zSWdZVtXT7E',
    synopsis: 'When Earth becomes uninhabitable, a farmer and ex-NASA pilot leads a mission through a wormhole to search for a new home for humanity, challenging the boundaries of space and time.',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    director: 'Christopher Nolan',
    smartLabel: 'All-Time Classic',
  },
  {
    title: 'The Martian',
    year: 2015,
    rating: 8.0,
    duration: '2h 21m',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    poster: { url: tmdbPoster('/AjV6mWEReuy4Of61Lnj5Xj704m8.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/BjV6mWEReuy4Of61Lnj5Xj704m8.jpg'), publicId: null },
    youtubeId: 'ej3ioOneTy8',
    synopsis: 'An astronaut becomes stranded on Mars after his crew assumes him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.',
    cast: ['Matt Damon', 'Jessica Chastain', 'Kristen Wiig', 'Jeff Daniels'],
    director: 'Ridley Scott',
    smartLabel: 'Optimistic Survival',
  },
  {
    title: 'Gravity',
    year: 2013,
    rating: 7.7,
    duration: '1h 31m',
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    poster: { url: tmdbPoster('/c6mWEReuy4Of61Lnj5Xj704m8.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/d6mWEReuy4Of61Lnj5Xj704m8.jpg'), publicId: null },
    youtubeId: 'OiTiKOy59o4',
    synopsis: 'Two astronauts work together to survive after an accident leaves them stranded in space.',
    cast: ['Sandra Bullock', 'George Clooney', 'Ed Harris', 'Orto Ignatiussen'],
    director: 'Alfonso Cuarón',
    smartLabel: 'Suspense Thriller',
  },
  {
    title: 'Ready Player One',
    year: 2018,
    rating: 7.4,
    duration: '2h 20m',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    poster: { url: tmdbPoster('/4j0HT416wKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/b7FFu5U4uKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'cSp1dM2Vj48',
    synopsis: 'When the creator of a virtual reality world called the OASIS dies, he releases a video in which he challenges all OASIS users to find his Easter Egg.',
    cast: ['Tye Sheridan', 'Olivia Cooke', 'Ben Mendelsohn', 'Lena Waithe'],
    director: 'Steven Spielberg',
    smartLabel: 'Cyber Adventure',
  },
  {
    title: 'Tenet',
    year: 2020,
    rating: 7.3,
    duration: '2h 30m',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    poster: { url: tmdbPoster('/6vxi0a1MXWM5tIfVmhJtZL0MKrI.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/7vxi0a1MXWM5tIfVmhJtZL0MKrI.jpg'), publicId: null },
    youtubeId: 'LdOM0x0xdwM',
    synopsis: 'Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage.',
    cast: ['John David Washington', 'Robert Pattinson', 'Elizabeth Debicki', 'Kenneth Branagh'],
    director: 'Christopher Nolan',
    smartLabel: 'Mind-Bending espionage',
  },
  {
    title: 'Tomorrowland',
    year: 2015,
    rating: 6.4,
    duration: '2h 10m',
    genres: ['Sci-Fi', 'Adventure', 'Family'],
    poster: { url: tmdbPoster('/8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'ln8-yN0HjI8',
    synopsis: 'Bound by a shared destiny, a bright, optimistic teen bursting with scientific curiosity and a former boy-genius inventor embark on a danger-filled mission.',
    cast: ['George Clooney', 'Hugh Laurie', 'Britt Robertson', 'Raffey Cassidy'],
    director: 'Brad Bird',
    smartLabel: 'Future Optimism',
  },
  {
    title: 'First Man',
    year: 2018,
    rating: 7.4,
    duration: '2h 21m',
    genres: ['Sci-Fi', 'Drama', 'History'],
    poster: { url: tmdbPoster('/u8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/v8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'w4RGSLBL2cY',
    synopsis: 'A look at the life of the astronaut, Neil Armstrong, and the legendary space mission that led him to become the first man to walk on the Moon.',
    cast: ['Ryan Gosling', 'Claire Foy', 'Jason Clarke', 'Kyle Chandler'],
    director: 'Damien Chazelle',
    smartLabel: 'Historical Thriller',
  },

  // ─── DRAMA (10) ───────────────────────────────────────────────────────────
  {
    title: 'The Holdovers',
    year: 2023,
    rating: 8.0,
    duration: '2h 13m',
    genres: ['Drama', 'Comedy'],
    poster: { url: tmdbPoster('/VHmCMFkDsGRlCCBgjAmzaTm0gw.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/hGK2m5CVNEW5GCwbKYEEIXjFkHh.jpg'), publicId: null },
    youtubeId: 'AhKEnFfMoHQ',
    synopsis: 'A curmudgeonly instructor at a New England prep school is forced to remain on campus during the Christmas break to look after a handful of students with nowhere to go — a holiday none of them will forget.',
    cast: ['Paul Giamatti', 'Dominic Sessa', 'Da\'Vine Joy Randolph', 'Carrie Preston'],
    director: 'Alexander Payne',
    smartLabel: 'Hidden Gem',
  },
  {
    title: 'Little Women',
    year: 2019,
    rating: 7.8,
    duration: '2h 15m',
    genres: ['Drama', 'Romance'],
    poster: { url: tmdbPoster('/d5mWEReuy4Of61Lnj5Xj704m8.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/e5mWEReuy4Of61Lnj5Xj704m8.jpg'), publicId: null },
    youtubeId: 'AST2-YqyM2s',
    synopsis: 'Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.',
    cast: ['Saoirse Ronan', 'Emma Watson', 'Florence Pugh', 'Eliza Scanlen'],
    director: 'Greta Gerwig',
    smartLabel: 'Inspiring Novel Adaptation',
  },
  {
    title: 'A Beautiful Day in the Neighborhood',
    year: 2019,
    rating: 7.2,
    duration: '1h 49m',
    genres: ['Drama', 'Biography'],
    poster: { url: tmdbPoster('/8Vt6mWEReuy4Of61Lnj5Xj70.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg'), publicId: null },
    youtubeId: '-VYEgpRLmPo',
    synopsis: 'Based on the true story of a real-life friendship between Fred Rogers and journalist Lloyd Vogel.',
    cast: ['Tom Hanks', 'Matthew Rhys', 'Susan Kelechi Watson', 'Chris Cooper'],
    director: 'Marielle Heller',
    smartLabel: 'Deeply Moving',
  },
  {
    title: 'Ford v Ferrari',
    year: 2019,
    rating: 8.1,
    duration: '2h 32m',
    genres: ['Drama', 'Action', 'Biography'],
    poster: { url: tmdbPoster('/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/2Y4nlOVLTFqOPjCRiubnFSJ5KRE.jpg'), publicId: null },
    youtubeId: 'I3h95Fs9KB8',
    synopsis: 'American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford.',
    cast: ['Matt Damon', 'Christian Bale', 'Jon Bernthal', 'Caitriona Balfe'],
    director: 'James Mangold',
    smartLabel: 'Highly Inspiring',
  },
  {
    title: 'Green Book',
    year: 2018,
    rating: 8.2,
    duration: '2h 10m',
    genres: ['Drama', 'Comedy', 'Biography'],
    poster: { url: tmdbPoster('/hlrpn9Qo5T4g65z5667104b2bH0.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/mhdeE1yShHTkWbjUR7v3CmtZs4N.jpg'), publicId: null },
    youtubeId: 'QkZoJdUuVwY',
    synopsis: 'A working-class Italian-American bouncer becomes the driver of an African-American classical pianist on a venue tour through the 1960s American South.',
    cast: ['Viggo Mortensen', 'Mahershala Ali', 'Linda Cardellini', 'Sebastian Maniscalco'],
    director: 'Peter Farrelly',
    smartLabel: 'Academy Award Winner',
  },
  {
    title: 'The Fabelmans',
    year: 2022,
    rating: 7.6,
    duration: '2h 31m',
    genres: ['Drama'],
    poster: { url: tmdbPoster('/4j0HT416wKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/a7FFu5U4uKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'D1G2i5_52pA',
    synopsis: 'Growing up in post-World War II era Arizona, young Sammy Fabelman aspires to become a filmmaker as he reaches adolescence, but soon discovers a shattering family secret.',
    cast: ['Gabriel LaBelle', 'Michelle Williams', 'Paul Dano', 'Seth Rogen'],
    director: 'Steven Spielberg',
    smartLabel: 'Autobiographical Drama',
  },
  {
    title: 'Hidden Figures',
    year: 2016,
    rating: 7.8,
    duration: '2h 7m',
    genres: ['Drama', 'History', 'Biography'],
    poster: { url: tmdbPoster('/pZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '5wfrDhgUMGI',
    synopsis: 'The story of a team of female African-American mathematicians who served a vital role in NASA during the early years of the U.S. space program.',
    cast: ['Taraji P. Henson', 'Octavia Spencer', 'Janelle Monáe', 'Kevin Costner'],
    director: 'Theodore Melfi',
    smartLabel: 'Powerful Truth',
  },
  {
    title: 'Wonder',
    year: 2017,
    rating: 8.0,
    duration: '1h 53m',
    genres: ['Drama', 'Family'],
    poster: { url: tmdbPoster('/8A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'ngiK1gQKGK8',
    synopsis: 'Based on the New York Times bestseller, this movie tells the incredibly inspiring and heartwarming story of August Pullman, a boy with facial differences who enters a mainstream elementary school.',
    cast: ['Jacob Tremblay', 'Owen Wilson', 'Julia Roberts', 'Izabela Vidovic'],
    director: 'Stephen Chbosky',
    smartLabel: 'Inspiring Family Film',
  },
  {
    title: 'We Bought a Zoo',
    year: 2011,
    rating: 7.1,
    duration: '2h 4m',
    genres: ['Drama', 'Family', 'Comedy'],
    poster: { url: tmdbPoster('/u8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/v8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'OP3wT8QeLhU',
    synopsis: 'Set in Southern California, a father moves his young family to a countryside house, which happens to contain a struggling zoo.',
    cast: ['Matt Damon', 'Scarlett Johansson', 'Thomas Haden Church', 'Colin Ford'],
    director: 'Cameron Crowe',
    smartLabel: 'Feel-Good Drama',
  },
  {
    title: 'King Richard',
    year: 2021,
    rating: 7.5,
    duration: '2h 24m',
    genres: ['Drama', 'Sport', 'Biography'],
    poster: { url: tmdbPoster('/pZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'BKP_0zUFNFY',
    synopsis: 'A look at how tennis superstars Venus and Serena Williams became who they are after the coaching from their father Richard Williams.',
    cast: ['Will Smith', 'Aunjanue Ellis', 'Saniyya Sidney', 'Demi Singleton'],
    director: 'Reinaldo Marcus Green',
    smartLabel: 'Oscar Winning Actor',
  },

  // ─── FANTASY (10) ──────────────────────────────────────────────────────────
  {
    title: 'Wicked',
    year: 2024,
    rating: 7.7,
    duration: '2h 40m',
    genres: ['Fantasy', 'Musical', 'Drama'],
    poster: { url: tmdbPoster('/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/uKb22E0nlzr914bA9KyA5CVCOlV.jpg'), publicId: null },
    youtubeId: 'vt98AlBDI9Y',
    synopsis: 'The story of the Witches of Oz — the unlikely friendship between Elphaba and Glinda, before Dorothy ever arrived in Oz. Their lives intertwine in ways that change them both forever.',
    cast: ['Cynthia Erivo', 'Ariana Grande', 'Jeff Goldblum', 'Jonathan Bailey'],
    director: 'Jon M. Chu',
    smartLabel: 'Spectacular Musical',
  },
  {
    title: 'Barbie',
    year: 2023,
    rating: 6.9,
    duration: '1h 54m',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    poster: { url: tmdbPoster('/iuFNMS8vlzmXFj3jqnWpxIQwDDb.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/nHf61UzkfFno5X1ofIjuPJuc21e.jpg'), publicId: null },
    youtubeId: 'pBk4NYhaPos',
    synopsis: 'Barbie suffers a crisis that leads her to question her world and her existence. She and Ken go on a journey of self-discovery in the real world, confronting reality and identity.',
    cast: ['Margot Robbie', 'Ryan Gosling', 'America Ferrera', 'Kate McKinnon'],
    director: 'Greta Gerwig',
    smartLabel: 'Cultural Phenomenon',
  },
  {
    title: 'Maleficent: Mistress of Evil',
    year: 2019,
    rating: 6.6,
    duration: '1h 58m',
    genres: ['Fantasy', 'Adventure', 'Family'],
    poster: { url: tmdbPoster('/4j0HT416wKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/b7FFu5U4uKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '5Z13e3uX-V0',
    synopsis: 'Maleficent and her goddaughter Aurora begin to question the complex family ties that bind them as they are pulled in different directions.',
    cast: ['Angelina Jolie', 'Elle Fanning', 'Michelle Pfeiffer', 'Chiwetel Ejiofor'],
    director: 'Joachim Rønning',
    smartLabel: 'Dark Fantasy',
  },
  {
    title: 'Cruella',
    year: 2021,
    rating: 7.3,
    duration: '2h 14m',
    genres: ['Comedy', 'Crime', 'Fantasy'],
    poster: { url: tmdbPoster('/pZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'gmRKv7n2UX8',
    synopsis: 'A live-action prequel feature film following a young grifter named Estella, who is determined to make a name for herself in London\'s fashion world.',
    cast: ['Emma Stone', 'Emma Thompson', 'Joel Fry', 'Paul Walter Hauser'],
    director: 'Craig Gillespie',
    smartLabel: 'Stylish Crime Comedy',
  },
  {
    title: 'Fantastic Beasts: The Secrets of Dumbledore',
    year: 2022,
    rating: 6.2,
    duration: '2h 22m',
    genres: ['Fantasy', 'Adventure'],
    poster: { url: tmdbPoster('/8A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'Y9nyw82e_DM',
    synopsis: 'Professor Albus Dumbledore knows the powerful Dark wizard Gellert Grindelwald is moving to seize control of the wizarding world.',
    cast: ['Eddie Redmayne', 'Jude Law', 'Ezra Miller', 'Mads Mikkelsen'],
    director: 'David Yates',
    smartLabel: 'Wizarding World',
  },
  {
    title: 'Stardust',
    year: 2007,
    rating: 7.6,
    duration: '2h 7m',
    genres: ['Fantasy', 'Adventure', 'Romance'],
    poster: { url: tmdbPoster('/u8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/v8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'Vz7SjXN7vOM',
    synopsis: 'In a countryside town bordering on a magical land, a young man promises his beloved to retrieve a fallen star by venturing into the magical realm.',
    cast: ['Charlie Cox', 'Claire Danes', 'Sienna Miller', 'Robert De Niro'],
    director: 'Matthew Vaughn',
    smartLabel: 'Cult Classic',
  },
  {
    title: 'Percy Jackson: Sea of Monsters',
    year: 2013,
    rating: 5.8,
    duration: '1h 46m',
    genres: ['Fantasy', 'Adventure', 'Family'],
    poster: { url: tmdbPoster('/pZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '5fB58P6_8KY',
    synopsis: 'In order to restore their dying safe haven, the son of Poseidon and his friends embark on a quest to the Sea of Monsters to find the mythical Golden Fleece.',
    cast: ['Logan Lerman', 'Alexandra Daddario', 'Douglas Smith', 'Leven Rambin'],
    director: 'Thor Freudenthal',
    smartLabel: 'Teen Fantasy',
  },
  {
    title: 'Alice in Wonderland',
    year: 2010,
    rating: 6.4,
    duration: '1h 48m',
    genres: ['Fantasy', 'Adventure', 'Family'],
    poster: { url: tmdbPoster('/x3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/w3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '9POCgSRVFs0',
    synopsis: 'Nineteen-year-old Alice returns to the magical world from her childhood adventure, where she reunites with her old friends and learns of her true destiny.',
    cast: ['Mia Wasikowska', 'Johnny Depp', 'Helena Bonham Carter', 'Anne Hathaway'],
    director: 'Tim Burton',
    smartLabel: 'Tim Burton Visuals',
  },
  {
    title: 'Cinderella',
    year: 2015,
    rating: 6.9,
    duration: '1h 45m',
    genres: ['Fantasy', 'Family', 'Drama'],
    poster: { url: tmdbPoster('/8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '20DF6w10ZWM',
    synopsis: 'When her father unexpectedly dies, young Ella finds herself at the mercy of her cruel stepmother and her scheming stepsisters.',
    cast: ['Lily James', 'Cate Blanchett', 'Richard Madden', 'Helena Bonham Carter'],
    director: 'Kenneth Branagh',
    smartLabel: 'Inspiring Fairytale',
  },
  {
    title: 'The BFG',
    year: 2016,
    rating: 6.4,
    duration: '1h 57m',
    genres: ['Fantasy', 'Family', 'Adventure'],
    poster: { url: tmdbPoster('/z3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/y3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'GZ0WyW4f-98',
    synopsis: 'An orphan girl befriends a benevolent giant, the Big Friendly Giant, who takes her to Giant Country, where they attempt to stop man-eating giants.',
    cast: ['Mark Rylance', 'Ruby Barnhill', 'Penelope Wilton', 'Jemaine Clement'],
    director: 'Steven Spielberg',
    smartLabel: 'Roald Dahl Tale',
  },

  // ─── MYSTERY (10) ──────────────────────────────────────────────────────────
  {
    title: 'Glass Onion: A Knives Out Mystery',
    year: 2022,
    rating: 7.1,
    duration: '2h 19m',
    genres: ['Mystery', 'Comedy', 'Thriller'],
    poster: { url: tmdbPoster('/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/6pO95yl9MgETUVwouwlOIdR9BX3.jpg'), publicId: null },
    youtubeId: 'CRCifcJ4Uqg',
    synopsis: 'Detective Benoit Blanc travels to Greece to unravel the layers of a mystery surrounding a tech billionaire and his carefully curated group of friends on a private island.',
    cast: ['Daniel Craig', 'Edward Norton', 'Janelle Monáe', 'Kate Hudson'],
    director: 'Rian Johnson',
    smartLabel: 'Whodunit Delight',
  },
  {
    title: 'Knives Out',
    year: 2019,
    rating: 7.9,
    duration: '2h 10m',
    genres: ['Mystery', 'Comedy', 'Drama'],
    poster: { url: tmdbPoster('/pZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'qGqiHJTsRkQ',
    synopsis: 'A detective investigates the death of a patriarch of an eccentric, combative family.',
    cast: ['Daniel Craig', 'Chris Evans', 'Ana de Armas', 'Jamie Lee Curtis'],
    director: 'Rian Johnson',
    smartLabel: 'Modern Whodunit',
  },
  {
    title: 'Murder on the Orient Express',
    year: 2017,
    rating: 6.7,
    duration: '1h 51m',
    genres: ['Mystery', 'Drama', 'Crime'],
    poster: { url: tmdbPoster('/8A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'Mq4m3yAoW8E',
    synopsis: 'When a murder occurs on the train on which he\'s travelling, celebrated detective Hercule Poirot is recruited to solve the case.',
    cast: ['Kenneth Branagh', 'Penélope Cruz', 'Willem Dafoe', 'Judi Dench'],
    director: 'Kenneth Branagh',
    smartLabel: 'Classic Murder Mystery',
  },
  {
    title: 'Death on the Nile',
    year: 2022,
    rating: 6.3,
    duration: '2h 7m',
    genres: ['Mystery', 'Drama', 'Crime'],
    poster: { url: tmdbPoster('/u8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/v8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'dZRqB0cOD-A',
    synopsis: 'While on vacation on the Nile, Hercule Poirot must investigate the murder of a young heiress.',
    cast: ['Kenneth Branagh', 'Gal Gadot', 'Armie Hammer', 'Emma Mackey'],
    director: 'Kenneth Branagh',
    smartLabel: 'Agatha Christie Tale',
  },
  {
    title: 'Enola Holmes',
    year: 2020,
    rating: 6.6,
    duration: '2h 3m',
    genres: ['Mystery', 'Adventure', 'Drama'],
    poster: { url: tmdbPoster('/pZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '1d0KphvXhA8',
    synopsis: 'When her mother disappears, Sherlock Holmes\' sister Enola goes on a mission to find her.',
    cast: ['Millie Bobby Brown', 'Henry Cavill', 'Sam Claflin', 'Helena Bonham Carter'],
    director: 'Harry Bradbeer',
    smartLabel: 'Teen Detective',
  },
  {
    title: 'Enola Holmes 2',
    year: 2022,
    rating: 6.7,
    duration: '2h 9m',
    genres: ['Mystery', 'Adventure', 'Drama'],
    poster: { url: tmdbPoster('/x3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/w3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'KKXegJFeJGo',
    synopsis: 'Now a detective-for-hire, Enola Holmes takes on her first official case to find a missing girl, as the sparks of a dangerous conspiracy ignite a mystery.',
    cast: ['Millie Bobby Brown', 'Henry Cavill', 'David Thewlis', 'Louis Partridge'],
    director: 'Harry Bradbeer',
    smartLabel: 'High Stakes Sequel',
  },
  {
    title: 'Sherlock Holmes: A Game of Shadows',
    year: 2011,
    rating: 7.4,
    duration: '2h 9m',
    genres: ['Mystery', 'Action', 'Adventure'],
    poster: { url: tmdbPoster('/8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'V17zXw8u1F4',
    synopsis: 'Sherlock Holmes and his sidekick Watson join forces to outwit and bring down their fiercest adversary, Professor Moriarty.',
    cast: ['Robert Downey Jr.', 'Jude Law', 'Jared Harris', 'Noomi Rapace'],
    director: 'Guy Ritchie',
    smartLabel: 'Guy Ritchie Action',
  },
  {
    title: 'Now You See Me',
    year: 2013,
    rating: 7.2,
    duration: '1h 55m',
    genres: ['Mystery', 'Thriller', 'Crime'],
    poster: { url: tmdbPoster('/z3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/y3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: '4OtM9j2VPrw',
    synopsis: 'An FBI agent and a French Interpol detective track a team of illusionists who pull off bank heists during their performances.',
    cast: ['Jesse Eisenberg', 'Common', 'Mark Ruffalo', 'Woody Harrelson'],
    director: 'Louis Leterrier',
    smartLabel: 'Illusionist Heist',
  },
  {
    title: 'Now You See Me 2',
    year: 2016,
    rating: 6.5,
    duration: '2h 9m',
    genres: ['Mystery', 'Action', 'Comedy'],
    poster: { url: tmdbPoster('/4j0HT416wKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/a7FFu5U4uKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'InqU8CLwb3g',
    synopsis: 'The Four Horsemen resurface, and are forcibly recruited by a tech genius to pull off their most impossible heist yet.',
    cast: ['Jesse Eisenberg', 'Mark Ruffalo', 'Woody Harrelson', 'Dave Franco'],
    director: 'Jon M. Chu',
    smartLabel: 'Action Magic Sequel',
  },
  {
    title: 'Missing',
    year: 2023,
    rating: 7.1,
    duration: '1h 51m',
    genres: ['Mystery', 'Thriller'],
    poster: { url: tmdbPoster('/pZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'seBiUtK9w4E',
    synopsis: 'After her mother disappears while on vacation in Colombia, June\'s search for answers is hindered by international red tape.',
    cast: ['Storm Reid', 'Nia Long', 'Ken Leung', 'Amy Landecker'],
    director: 'Will Merrick & Nick Johnson',
    smartLabel: 'Modern Screen-Life',
  },

  // ─── THRILLER (10) ─────────────────────────────────────────────────────────
  {
    title: 'Twisters',
    year: 2024,
    rating: 7.2,
    duration: '2h 2m',
    genres: ['Thriller', 'Action', 'Adventure'],
    poster: { url: tmdbPoster('/pjnD08NmLEhuaf29S664Zl5Y8Jb.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/7LGkNhBQMkE9tBJFhSJK4pGOKPi.jpg'), publicId: null },
    youtubeId: 'aHEgtXhOQRQ',
    synopsis: 'Storm chasers race across the Great Plains to test a new system that could neutralize the destructive power of tornadoes, while competing agendas put everyone at risk.',
    cast: ['Daisy Edgar-Jones', 'Glen Powell', 'Anthony Ramos', 'Maura Tierney'],
    director: 'Lee Isaac Chung',
    smartLabel: 'Edge of Your Seat',
  },
  {
    title: 'Oppenheimer',
    year: 2023,
    rating: 8.3,
    duration: '3h 0m',
    genres: ['Mystery', 'Drama', 'History'],
    poster: { url: tmdbPoster('/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg'), publicId: null },
    youtubeId: 'uYPbbksJxIg',
    synopsis: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II, told through the lens of his subsequent security hearing.',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    director: 'Christopher Nolan',
    smartLabel: 'Award-Winning',
  },
  {
    title: 'A Quiet Place: Day One',
    year: 2024,
    rating: 6.9,
    duration: '1h 39m',
    genres: ['Thriller', 'Sci-Fi', 'Drama'],
    poster: { url: tmdbPoster('/8A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9A3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'YPY7J-g1yv8',
    synopsis: 'Experience the day the world went silent in this thriller following a woman trying to survive the arrival of blind extraterrestrial creatures in New York.',
    cast: ['Lupita Nyong\'o', 'Joseph Quinn', 'Alex Wolff', 'Djimon Hounsou'],
    director: 'Michael Sarnoski',
    smartLabel: 'Sensational Suspense',
  },
  {
    title: 'A Quiet Place Part II',
    year: 2020,
    rating: 7.2,
    duration: '1h 37m',
    genres: ['Thriller', 'Sci-Fi'],
    poster: { url: tmdbPoster('/u8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/v8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'WR7cc5t7tSw',
    synopsis: 'Following the events at home, the Abbott family must now face the terrors of the outside world as they continue their fight for survival in silence.',
    cast: ['Emily Blunt', 'Millicent Simmonds', 'Cillian Murphy', 'Noah Jupe'],
    director: 'John Krasinski',
    smartLabel: 'Survival Thriller',
  },
  {
    title: 'Fall',
    year: 2022,
    rating: 6.4,
    duration: '1h 47m',
    genres: ['Thriller'],
    poster: { url: tmdbPoster('/pZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'aa5M2_xY1v8',
    synopsis: 'Best friends Becky and Hunter find themselves at the top of a 2,000-foot radio tower with no way down and no cell reception.',
    cast: ['Grace Caroline Currey', 'Virginia Gardner', 'Jeffrey Dean Morgan', 'Mason Gooding'],
    director: 'Scott Mann',
    smartLabel: 'Terrifying Heights',
  },
  {
    title: 'Captain Phillips',
    year: 2013,
    rating: 7.8,
    duration: '2h 14m',
    genres: ['Thriller', 'Drama', 'Action'],
    poster: { url: tmdbPoster('/x3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/w3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'Sp6Je1t6B48',
    synopsis: 'The true story of Captain Richard Phillips and the 2009 hijacking by Somali pirates of the US-flagged MV Maersk Alabama, the first American cargo ship to be hijacked in two hundred years.',
    cast: ['Tom Hanks', 'Barkhad Abdi', 'Catherine Keener', 'Barkhad Abdirahman'],
    director: 'Paul Greengrass',
    smartLabel: 'High Tension Realist',
  },
  {
    title: 'Sully',
    year: 2016,
    rating: 7.4,
    duration: '1h 36m',
    genres: ['Thriller', 'Drama', 'History'],
    poster: { url: tmdbPoster('/8X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/9X2mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'mjKEXxO2KGE',
    synopsis: 'The story of Chesley "Sully" Sullenberger, who became a hero after gliding his plane along the water of the Hudson River, saving all 155 passengers and crew.',
    cast: ['Tom Hanks', 'Aaron Eckhart', 'Laura Linney', 'Valerie Mahaffey'],
    director: 'Clint Eastwood',
    smartLabel: 'Inspiring Heroism',
  },
  {
    title: 'The Walk',
    year: 2015,
    rating: 7.3,
    duration: '2h 3m',
    genres: ['Thriller', 'Drama', 'Adventure'],
    poster: { url: tmdbPoster('/z3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/y3qWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'GR1emq8V2yQ',
    synopsis: 'In 1974, French high-wire artist Philippe Petit attempts to walk on a tightrope strung between the World Trade Center towers.',
    cast: ['Joseph Gordon-Levitt', 'Charlotte Le Bon', 'Ben Kingsley', 'Guillaume Baillargeon'],
    director: 'Robert Zemeckis',
    smartLabel: 'Stunning Visuals',
  },
  {
    title: 'Non-Stop',
    year: 2014,
    rating: 6.9,
    duration: '1h 46m',
    genres: ['Thriller', 'Action', 'Mystery'],
    poster: { url: tmdbPoster('/4j0HT416wKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/a7FFu5U4uKO2jZFS7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'jiHDHp-fK54',
    synopsis: 'An air marshal springs into action during a transatlantic flight after receiving a series of text messages demanding $150 million.',
    cast: ['Liam Neeson', 'Julianne Moore', 'Scoot McNairy', 'Michelle Dockery'],
    director: 'Jaume Collet-Serra',
    smartLabel: ' Liam Neeson Action',
  },
  {
    title: 'Dunkirk',
    year: 2017,
    rating: 7.8,
    duration: '1h 46m',
    genres: ['Thriller', 'Drama', 'History'],
    poster: { url: tmdbPoster('/pZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    backdrop: { url: tmdbBackdrop('/qZ8mWE7v3Uz4m4e2u.jpg'), publicId: null },
    youtubeId: 'F-eMt3SrfFU',
    synopsis: 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.',
    cast: ['Fionn Whitehead', 'Tom Glynn-Carney', 'Jack Lowden', 'Harry Styles'],
    director: 'Christopher Nolan',
    smartLabel: 'Tense Cinematic Triumph',
  },
];

/**
 * Seed function — clears existing movies and inserts the full balanced catalog.
 * Run with: node server/seed/seedMovies.js
 */
async function seedMovieCatalog() {
  try {
    const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/StreamFlix';
    await mongoose.connect(mongoUri);
    console.log('📦 Connected to MongoDB');

    await Movie.deleteMany({});
    console.log('🗑️  Cleared existing movie collection');

    await Movie.insertMany(movieCatalog);
    console.log(`✅ Successfully seeded ${movieCatalog.length} movies`);
    console.log('📊 Genre breakdown: 10 movies per category across 9 genres');

    await mongoose.disconnect();
    process.exit(0);
  } catch (seedError) {
    console.error('❌ Seed error:', seedError);
    process.exit(1);
  }
}

seedMovieCatalog();
