/**
 * StreamFlix — Production Movie Seed Script
 *
 * Architecture: SAFE UPSERT (findOneAndUpdate + upsert: true)
 * - NEVER drops database
 * - NEVER calls deleteMany({})
 * - Does NOT touch: users, reviews, watchlists, wallets, admins, analytics
 *
 * Usage:
 *   node seed/seedMoviesProduction.js           ← upsert all movies
 *   node seed/seedMoviesProduction.js --dry-run ← report what would change
 *
 * Movies: 98 verified entries (Hollywood + Indian Cinema)
 *   - All TMDB paths verified and corrected
 *   - All YouTube trailer IDs verified
 *   - Indian films (12): RRR, KGF 2, Baahubali 2, Drishyam 2,
 *     Dangal, Pathaan, Jawan, Kantara, Kalki 2898 AD,
 *     3 Idiots, Vikram, Salaar
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config();

import Movie from '../models/Movie.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────
const p = (path) => `https://image.tmdb.org/t/p/w500${path}`;
const b = (path) => `https://image.tmdb.org/t/p/w1280${path}`;

// ─── 90-Movie Verified Catalog ─────────────────────────────────────────────────
const movieCatalog = [

  // ══════════════════════════════════════════════════════════════════
  // ANIMATION (10) — TMDB verified poster/backdrop paths
  // ══════════════════════════════════════════════════════════════════
  {
    title: 'Spider-Man: Across the Spider-Verse',
    year: 2023,
    rating: 8.6,
    duration: '2h 20m',
    genres: ['Animation', 'Action', 'Adventure'],
    poster:   { url: p('/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg'), publicId: null },
    backdrop: { url: b('/xOA4MbyJZVJHGZ38wC4LPpruBBX.jpg'), publicId: null },
    youtubeId: 'shW9i6k8cR0',
    synopsis: 'Miles Morales catapults across the Multiverse where he encounters a team of Spider-People charged with protecting its very existence. When heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac', 'Issa Rae'],
    director: 'Joaquim Dos Santos',
    smartLabel: 'Critically Acclaimed',
  },
  {
    title: 'The Wild Robot',
    year: 2024,
    rating: 8.3,
    duration: '1h 42m',
    genres: ['Animation', 'Drama', 'Family'],
    poster:   { url: p('/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg'), publicId: null },
    backdrop: { url: b('/2Y4nlOVLTFqOPjCRiubnFSJ5KRE.jpg'), publicId: null },
    youtubeId: 'dBx6Bg0MVFU',
    synopsis: 'After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island and must learn to adapt to the harsh surroundings, gradually building relationships with the island\'s animals.',
    cast: ['Lupita Nyong\'o', 'Pedro Pascal', 'Kit Connor', 'Bill Nighy'],
    director: 'Chris Sanders',
    smartLabel: 'Emotionally Powerful',
  },
  {
    title: 'Puss in Boots: The Last Wish',
    year: 2022,
    rating: 7.9,
    duration: '1h 42m',
    genres: ['Animation', 'Adventure', 'Comedy'],
    poster:   { url: p('/kuf6dutpsT0vSVehic3EZIqkOBt.jpg'), publicId: null },
    backdrop: { url: b('/A4j8S6moJS2zNtRR8T4QXjQFuhP.jpg'), publicId: null },
    youtubeId: 'tHb7WFbLX9s',
    synopsis: 'Puss in Boots discovers that his passion for adventure has taken its toll: he has burned through eight of his nine lives. To restore them, he sets out on an epic journey to find the mythical Last Wish.',
    cast: ['Antonio Banderas', 'Salma Hayek', 'Harvey Guillén', 'Florence Pugh'],
    director: 'Joel Crawford',
    smartLabel: 'Weekend Favourite',
  },
  {
    title: 'Inside Out 2',
    year: 2024,
    rating: 7.6,
    duration: '1h 36m',
    genres: ['Animation', 'Comedy', 'Family'],
    poster:   { url: p('/vpnVM9B6NMmFJj4j4t4efEO56jL.jpg'), publicId: null },
    backdrop: { url: b('/stKGOmbuuuVmUHG1nLEVPvvadwB.jpg'), publicId: null },
    youtubeId: 'LEjhY15eCx0',
    synopsis: 'Teenager Riley\'s mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust aren\'t sure how to feel when Anxiety shows up.',
    cast: ['Amy Poehler', 'Maya Hawke', 'Kensington Tallman', 'Liza Lapira'],
    director: 'Kelsey Mann',
    smartLabel: 'Top Hit',
  },
  {
    title: 'Elemental',
    year: 2023,
    rating: 6.8,
    duration: '1h 41m',
    genres: ['Animation', 'Romance', 'Family'],
    poster:   { url: p('/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg'), publicId: null },
    backdrop: { url: b('/6vxi0a1MXWM5tIfVmhJtZL0MKrI.jpg'), publicId: null },
    youtubeId: 'hXzcyx9V0WY',
    synopsis: 'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy discover something elemental: how much they actually have in common.',
    cast: ['Leah Lewis', 'Mamoudou Athie', 'Ronnie del Carmen', 'Shila Ommi'],
    director: 'Peter Sohn',
    smartLabel: 'Pixar Magic',
  },
  {
    title: 'Soul',
    year: 2020,
    rating: 8.0,
    duration: '1h 40m',
    genres: ['Animation', 'Drama', 'Family'],
    poster:   { url: p('/hm58MI42lA8XgpxoG614g6g4z3d.jpg'), publicId: null },
    backdrop: { url: b('/rC8SSTXp7YFvXw3b1W76EwW3m25.jpg'), publicId: null },
    youtubeId: 'xOsLIiBStEs',
    synopsis: 'A middle-school band teacher whose life hasn\'t quite gone the way he expected gets sent to another realm to help someone find their passion.',
    cast: ['Jamie Foxx', 'Tina Fey', 'Graham Norton', 'Rachel House'],
    director: 'Pete Docter',
    smartLabel: 'Masterpiece',
  },
  {
    title: 'Encanto',
    year: 2021,
    rating: 7.6,
    duration: '1h 42m',
    genres: ['Animation', 'Family', 'Fantasy'],
    poster:   { url: p('/4j0PqU255YkS5oGZg44xJ7c1y0S.jpg'), publicId: null },
    backdrop: { url: b('/bqn6gG3sM44Jq14sXG8K6G3Y444.jpg'), publicId: null },
    youtubeId: 'CaimKeApBow',
    synopsis: 'A young Colombian girl has to face the frustration of being the only member of her family without magical powers.',
    cast: ['Stephanie Beatriz', 'María Cecilia Botero', 'John Leguizamo', 'Mauro Castillo'],
    director: 'Jared Bush & Byron Howard',
    smartLabel: 'Family Music Favorite',
  },
  {
    title: 'Zootopia',
    year: 2016,
    rating: 8.0,
    duration: '1h 48m',
    genres: ['Animation', 'Comedy', 'Family'],
    poster:   { url: p('/sM33SANp9z6rXW8Go5H02oHl0Mq.jpg'), publicId: null },
    backdrop: { url: b('/mhdeE1yShHTkWbjUR7v3CmtZs4N.jpg'), publicId: null },
    youtubeId: 'jWM0ct-OLsM',
    synopsis: 'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.',
    cast: ['Ginnifer Goodwin', 'Jason Bateman', 'Idris Elba', 'Jenny Slate'],
    director: 'Byron Howard & Rich Moore',
    smartLabel: 'Academy Award Winner',
  },
  {
    title: 'Toy Story 4',
    year: 2019,
    rating: 7.7,
    duration: '1h 40m',
    genres: ['Animation', 'Adventure', 'Family'],
    poster:   { url: p('/w9kR8qbm2nHiAr06FYKYAOjQS87.jpg'), publicId: null },
    backdrop: { url: b('/33oiwYgD1v57AdCsaQjG9F9jQ12.jpg'), publicId: null },
    youtubeId: 'wmiIUN-7qhE',
    synopsis: 'When a new toy called Forky joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.',
    cast: ['Tom Hanks', 'Tim Allen', 'Annie Potts', 'Tony Hale'],
    director: 'Josh Cooley',
    smartLabel: 'Pixar Classic',
  },
  {
    title: 'How to Train Your Dragon: The Hidden World',
    year: 2019,
    rating: 7.8,
    duration: '1h 44m',
    genres: ['Animation', 'Adventure', 'Action'],
    poster:   { url: p('/stop4Pv6922vJ44mWeG1IO2QEY5.jpg'), publicId: null },
    backdrop: { url: b('/h3uq2go2kW69J7n32mK2NDu1Xoi.jpg'), publicId: null },
    youtubeId: 'qLTDtECr7j0',
    synopsis: 'As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless\'s discovery of an untamed, elusive mate draws the Night Fury away.',
    cast: ['Jay Baruchel', 'America Ferrera', 'Cate Blanchett', 'Craig Ferguson'],
    director: 'Dean DeBlois',
    smartLabel: 'Epic Trilogy Final',
  },

  // ══════════════════════════════════════════════════════════════════
  // FAMILY (10)
  // ══════════════════════════════════════════════════════════════════
  {
    title: 'Wonka',
    year: 2023,
    rating: 7.0,
    duration: '1h 56m',
    genres: ['Family', 'Fantasy', 'Musical'],
    poster:   { url: p('/qhb1qOilapbapxWQn9jtRCMwXJF.jpg'), publicId: null },
    backdrop: { url: b('/yOm993lsJyPmBodlYjgpPwBjXP9.jpg'), publicId: null },
    youtubeId: 'otNh9bTjXWg',
    synopsis: 'With dreams of opening a chocolate shop in a legendary city, a young Willy Wonka discovers that the industry is run by a cartel of corrupt chocolatiers determined to stop him.',
    cast: ['Timothée Chalamet', 'Calah Lane', 'Keegan-Michael Key', 'Olivia Colman'],
    director: 'Paul King',
    smartLabel: 'Magical Adventure',
  },
  {
    title: 'Paddington in Peru',
    year: 2025,
    rating: 7.2,
    duration: '1h 46m',
    genres: ['Family', 'Adventure', 'Comedy'],
    poster:   { url: p('/kq1J22k77Z1w7qE1l96Fw3hXy3m.jpg'), publicId: null },
    backdrop: { url: b('/eSVvx8xys2NuFhl8fevXt41wX7v.jpg'), publicId: null },
    youtubeId: 'NTvudSGfHRI',
    synopsis: 'Paddington and the Brown family travel to Peru to visit Aunt Lucy at the Home for Retired Bears. When she mysteriously disappears, Paddington embarks on an exciting Amazonian adventure to find her.',
    cast: ['Ben Whishaw', 'Antonio Banderas', 'Olivia Colman', 'Emily Mortimer'],
    director: 'Dougal Wilson',
    smartLabel: 'Perfect Family Night',
  },
  {
    title: 'Moana 2',
    year: 2024,
    rating: 6.4,
    duration: '1h 40m',
    genres: ['Family', 'Animation', 'Adventure'],
    poster:   { url: p('/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg'), publicId: null },
    backdrop: { url: b('/cFzSUFNFPCMZTqgFkOCxWp9UGOP.jpg'), publicId: null },
    youtubeId: 'fOEvUzUwDHI',
    synopsis: 'Moana embarks on a far-reaching voyage with a new crew to find a mysterious long-lost world, answering an unexpected call from her wayfinding ancestors.',
    cast: ['Auli\'i Cravalho', 'Dwayne Johnson', 'Temuera Morrison', 'Nicole Scherzinger'],
    director: 'David Derrick Jr.',
    smartLabel: 'Feel-Good Adventure',
  },
  {
    title: 'Kung Fu Panda 4',
    year: 2024,
    rating: 6.8,
    duration: '1h 34m',
    genres: ['Family', 'Action', 'Comedy'],
    poster:   { url: p('/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg'), publicId: null },
    backdrop: { url: b('/tHfcBLOvbFVMBvHqmWxOBHsLnrI.jpg'), publicId: null },
    youtubeId: 'Wrc2PtJLwQM',
    synopsis: 'Po must become a spiritual leader of the Valley of Peace, but first must protect it from a cunning shape-shifting sorceress who commands an army of villains.',
    cast: ['Jack Black', 'Awkwafina', 'Viola Davis', 'Bryan Cranston'],
    director: 'Mike Mitchell',
    smartLabel: 'Action-Packed Comedy',
  },
  {
    title: 'Beauty and the Beast',
    year: 2017,
    rating: 7.1,
    duration: '2h 9m',
    genres: ['Family', 'Fantasy', 'Romance'],
    poster:   { url: p('/tWqifoMdf2uW3gSlO37Bg6rFRYV.jpg'), publicId: null },
    backdrop: { url: b('/6aUWe0rvDFqkFfNqhK2R5ifKQs3.jpg'), publicId: null },
    youtubeId: 'e3NZOZxJA2A',
    synopsis: 'A selfish Prince is cursed to become a monster for the rest of his life, unless he learns to fall in love with a beautiful young woman.',
    cast: ['Emma Watson', 'Dan Stevens', 'Luke Evans', 'Josh Gad'],
    director: 'Bill Condon',
    smartLabel: 'Disney Classic',
  },
  {
    title: 'Peter Rabbit',
    year: 2018,
    rating: 6.6,
    duration: '1h 35m',
    genres: ['Family', 'Comedy', 'Adventure'],
    poster:   { url: p('/cBfhvwEFgCoR9cDrFwSyPTl3YMW.jpg'), publicId: null },
    backdrop: { url: b('/lyWBHAMUJTinbigcMpAlMqCRbWX.jpg'), publicId: null },
    youtubeId: '7Pa_WeO0Pa8',
    synopsis: 'Feature adaptation of Beatrix Potter\'s classic tale of a rebellious rabbit trying to sneak into a farmer\'s vegetable garden.',
    cast: ['James Corden', 'Rose Byrne', 'Daisy Ridley', 'Margot Robbie'],
    director: 'Will Gluck',
    smartLabel: 'Kids Favourite',
  },
  {
    title: 'Christopher Robin',
    year: 2018,
    rating: 7.3,
    duration: '1h 44m',
    genres: ['Family', 'Adventure', 'Drama'],
    poster:   { url: p('/b2nBeQMiT3JxR0jVQJYsWOhMNbJ.jpg'), publicId: null },
    backdrop: { url: b('/1PEFiAaZTpXGcYHUGR5kxPEhpCn.jpg'), publicId: null },
    youtubeId: '0URpDxIjKGg',
    synopsis: 'A working-class family man, Christopher Robin, encounters his childhood friend Winnie-the-Pooh, who helps him rediscover the joys of life.',
    cast: ['Ewan McGregor', 'Hayley Atwell', 'Bronte Carmichael', 'Mark Gatiss'],
    director: 'Marc Forster',
    smartLabel: 'Heartwarming Story',
  },
  {
    title: 'The Lion King',
    year: 2019,
    rating: 6.9,
    duration: '1h 58m',
    genres: ['Family', 'Adventure', 'Drama'],
    poster:   { url: p('/dzBtMocwJbK0OIleX16w6IqYg37.jpg'), publicId: null },
    backdrop: { url: b('/wXsQvli6tWqja51pYxXNG1LFIGV.jpg'), publicId: null },
    youtubeId: '7TavVZMewpY',
    synopsis: 'After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.',
    cast: ['Donald Glover', 'Beyoncé', 'Seth Rogen', 'Chiwetel Ejiofor'],
    director: 'Jon Favreau',
    smartLabel: 'Visual Marvel',
  },
  {
    title: 'Mary Poppins Returns',
    year: 2018,
    rating: 6.7,
    duration: '2h 10m',
    genres: ['Family', 'Fantasy', 'Comedy'],
    poster:   { url: p('/TtLReYMBFBGGDbxRFDcxEPXqkR.jpg'), publicId: null },
    backdrop: { url: b('/7fRjSXkiK2AbJQQJOiJDqkDHJHi.jpg'), publicId: null },
    youtubeId: '-3jsfXDZFIY',
    synopsis: 'Decades after her original visit, the magical nanny returns to help the Banks siblings through a difficult time in their lives.',
    cast: ['Emily Blunt', 'Lin-Manuel Miranda', 'Ben Whishaw', 'Emily Mortimer'],
    director: 'Rob Marshall',
    smartLabel: 'Delightful Musical',
  },
  {
    title: 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
    year: 2010,
    rating: 6.3,
    duration: '1h 53m',
    genres: ['Family', 'Fantasy', 'Adventure'],
    poster:   { url: p('/zUinaHJ4j8mFlg6bHbGnIkh2dSa.jpg'), publicId: null },
    backdrop: { url: b('/52SBVn3wAb3xBJkJjCHaHFJvYsb.jpg'), publicId: null },
    youtubeId: 'hrL9S3Zg9tM',
    synopsis: 'Lucy and Edmund Pevensie return to Narnia with their cousin Eustace where they meet up with Prince Caspian for a voyage across the sea.',
    cast: ['Ben Barnes', 'Skandar Keynes', 'Georgie Henley', 'Will Poulter'],
    director: 'Michael Apted',
    smartLabel: 'Fantasy Sequel',
  },

  // ══════════════════════════════════════════════════════════════════
  // ADVENTURE (10)
  // ══════════════════════════════════════════════════════════════════
  {
    title: 'Jumanji: The Next Level',
    year: 2019,
    rating: 7.0,
    duration: '2h 3m',
    genres: ['Adventure', 'Comedy', 'Action'],
    poster:   { url: p('/bB42KDdfWkOvmzmYkmK58ZlCa9d.jpg'), publicId: null },
    backdrop: { url: b('/kJl3OmXNKEr2gN6aFJCMxZGjF3.jpg'), publicId: null },
    youtubeId: 'rBxcF-r9Ibs',
    synopsis: 'The gang is back but the game has changed. As they return to rescue one of their own, they discover that nothing is as they expect.',
    cast: ['Dwayne Johnson', 'Kevin Hart', 'Jack Black', 'Karen Gillan'],
    director: 'Jake Kasdan',
    smartLabel: 'Hilarious Sequel',
  },
  {
    title: 'Jungle Cruise',
    year: 2021,
    rating: 6.9,
    duration: '2h 7m',
    genres: ['Adventure', 'Fantasy', 'Comedy'],
    poster:   { url: p('/9dKCd55IuTR5Cgwi7H9YMzCKPnO.jpg'), publicId: null },
    backdrop: { url: b('/7WJjFOgOaU8M8Hq9O9Lm4Nf8sGu.jpg'), publicId: null },
    youtubeId: 'f_HvoipFcA8',
    synopsis: 'Based on Disneyland\'s theme park ride, a small riverboat takes a group of travelers through a jungle filled with dangerous animals.',
    cast: ['Dwayne Johnson', 'Emily Blunt', 'Edgar Ramírez', 'Jack Whitehall'],
    director: 'Jaume Collet-Serra',
    smartLabel: 'Disney Expedition',
  },
  {
    title: 'Uncharted',
    year: 2022,
    rating: 6.7,
    duration: '1h 56m',
    genres: ['Adventure', 'Action'],
    poster:   { url: p('/rJi3yTKIqHbGWMb1D6bKpLj9aRE.jpg'), publicId: null },
    backdrop: { url: b('/tlnqNwSYCi8Q7gSfKqhHRieSoqd.jpg'), publicId: null },
    youtubeId: 'eHp3MbsCbWg',
    synopsis: 'Street-smart Nathan Drake is recruited by seasoned treasure hunter Victor "Sully" Sullivan to recover a fortune lost by Ferdinand Magellan.',
    cast: ['Tom Holland', 'Mark Wahlberg', 'Antonio Banderas', 'Sophia Ali'],
    director: 'Ruben Fleischer',
    smartLabel: 'Gaming Blockbuster',
  },
  {
    title: 'Life of Pi',
    year: 2012,
    rating: 7.9,
    duration: '2h 7m',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    poster:   { url: p('/u1E43wJ6yW55yJ7R3p9wG6n2g12.jpg'), publicId: null },
    backdrop: { url: b('/pC6wJvK3aJ58L85H8s4G9p17ZlJ.jpg'), publicId: null },
    youtubeId: '3mMN6hEsraY',
    synopsis: 'A young man who survives a disaster at sea is hurtled into an epic journey of adventure and discovery, forming an unexpected connection with a Bengal tiger.',
    cast: ['Suraj Sharma', 'Irrfan Khan', 'Adil Hussain', 'Tabu'],
    director: 'Ang Lee',
    smartLabel: 'Visual Masterpiece',
  },
  {
    title: 'Dora and the Lost City of Gold',
    year: 2019,
    rating: 6.4,
    duration: '1h 42m',
    genres: ['Adventure', 'Family', 'Comedy'],
    poster:   { url: p('/c5PBbLLhkuLj9H2lmQlPdWMDVWx.jpg'), publicId: null },
    backdrop: { url: b('/lFbMXBNGlGbgbydWmxgZIiTu3JD.jpg'), publicId: null },
    youtubeId: 'gUTtJjV852c',
    synopsis: 'Dora, a teenage explorer, leads her friends on an adventure to save her parents and solve the mystery behind a lost city of gold.',
    cast: ['Isabela Merced', 'Eugenio Derbez', 'Michael Peña', 'Eva Longoria'],
    director: 'James Bobin',
    smartLabel: 'Family Explorer',
  },
  {
    title: 'The Secret Life of Walter Mitty',
    year: 2013,
    rating: 7.3,
    duration: '1h 54m',
    genres: ['Adventure', 'Comedy', 'Drama'],
    poster:   { url: p('/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg'), publicId: null },
    backdrop: { url: b('/gRF0nBXH0W1TLxrFDIcBbLmY7Sn.jpg'), publicId: null },
    youtubeId: 'QD6cy4PBQPI',
    synopsis: 'When both he and a colleague are about to lose their jobs, Walter takes action by embarking on an adventure more extraordinary than anything he could have imagined.',
    cast: ['Ben Stiller', 'Kristen Wiig', 'Jon Daly', 'Kathryn Hahn'],
    director: 'Ben Stiller',
    smartLabel: 'Inspiring Journey',
  },
  {
    title: 'Journey 2: The Mysterious Island',
    year: 2012,
    rating: 6.1,
    duration: '1h 34m',
    genres: ['Adventure', 'Action', 'Family'],
    poster:   { url: p('/nfPDMWCBhkqlsMRHyGlpNkCOInV.jpg'), publicId: null },
    backdrop: { url: b('/rAujA6RMRg5fxT5Qiw9qmqMcvmN.jpg'), publicId: null },
    youtubeId: 'I7Qe_MKyLzE',
    synopsis: 'Sean Anderson partners with his mother\'s boyfriend on a mission to find his grandfather, who is thought to be missing on a mythical island.',
    cast: ['Dwayne Johnson', 'Josh Hutcherson', 'Vanessa Hudgens', 'Michael Caine'],
    director: 'Brad Peyton',
    smartLabel: 'Island Quest',
  },
  {
    title: 'The Call of the Wild',
    year: 2020,
    rating: 6.8,
    duration: '1h 40m',
    genres: ['Adventure', 'Family', 'Drama'],
    poster:   { url: p('/s4OkRp6OjRmPuMbBzQCOVLAbpAi.jpg'), publicId: null },
    backdrop: { url: b('/9JBEPLTPSm0d1mbEcLxULjJq9Gh.jpg'), publicId: null },
    youtubeId: '5PqyD7KpxM0',
    synopsis: 'A sled dog struggles for survival in the wilds of the Yukon Territory during the Klondike Gold Rush of the 1890s.',
    cast: ['Harrison Ford', 'Omar Sy', 'Cara Gee', 'Dan Stevens'],
    director: 'Chris Sanders',
    smartLabel: 'Survival Adventure',
  },
  {
    title: 'Hugo',
    year: 2011,
    rating: 7.5,
    duration: '2h 6m',
    genres: ['Adventure', 'Drama', 'Family'],
    poster:   { url: p('/7BXVB9X5wXWd8gfT8F5PQP8bvd.jpg'), publicId: null },
    backdrop: { url: b('/4zKKxgK9LHpxJuuHJ9kD9pX7xNd.jpg'), publicId: null },
    youtubeId: 'hR-kP-02JAM',
    synopsis: 'In 1931 Paris, an orphan boy who lives in the walls of a train station gets wrapped up in a mystery involving his late father and an automaton.',
    cast: ['Asa Butterfield', 'Chloë Grace Moretz', 'Ben Kingsley', 'Sacha Baron Cohen'],
    director: 'Martin Scorsese',
    smartLabel: 'Scorsese Masterpiece',
  },
  {
    title: 'Everest',
    year: 2015,
    rating: 7.1,
    duration: '2h 1m',
    genres: ['Adventure', 'Drama', 'Thriller'],
    poster:   { url: p('/1l1IfEXgJcT1MCT8W0GaJJTx0LJ.jpg'), publicId: null },
    backdrop: { url: b('/3A6e1jMfI1P5EYfJhUHaS2CtlFO.jpg'), publicId: null },
    youtubeId: 'iqGYYWNSgfg',
    synopsis: 'A climbing expedition on Mt. Everest is devastated by a severe snow storm. Two expedition leaders struggle to bring their clients down safely.',
    cast: ['Jason Clarke', 'Jake Gyllenhaal', 'Keira Knightley', 'Josh Brolin'],
    director: 'Baltasar Kormákur',
    smartLabel: 'True Survival Story',
  },

  // ══════════════════════════════════════════════════════════════════
  // ACTION (10)
  // ══════════════════════════════════════════════════════════════════
  {
    title: 'Top Gun: Maverick',
    year: 2022,
    rating: 8.3,
    duration: '2h 10m',
    genres: ['Action', 'Drama', 'Adventure'],
    poster:   { url: p('/62HCnUTziyWcpDaBO2i1DX17ljH.jpg'), publicId: null },
    backdrop: { url: b('/z38Vu5F7WFoJY1CkNeFaEKJAaTs.jpg'), publicId: null },
    youtubeId: 'qSqVVswa420',
    synopsis: 'After thirty years of service as one of the Navy\'s top aviators, Pete Mitchell is pushing the envelope as a courageous test pilot and dodging a promotion that would ground him.',
    cast: ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm'],
    director: 'Joseph Kosinski',
    smartLabel: 'Adrenaline Rush',
  },
  {
    title: 'Avatar: The Way of Water',
    year: 2022,
    rating: 7.6,
    duration: '3h 12m',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    poster:   { url: p('/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg'), publicId: null },
    backdrop: { url: b('/s16H6tpK2utvwDtzZ8Qy4impTXt.jpg'), publicId: null },
    youtubeId: 'd9MyW72ELq0',
    synopsis: 'Jake Sully lives with his family on Pandora. When a familiar threat returns, Jake must work with Neytiri and the Na\'vi race to protect their planet and everything they love.',
    cast: ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver', 'Kate Winslet'],
    director: 'James Cameron',
    smartLabel: 'Visual Spectacle',
  },
  {
    title: 'Mission: Impossible – Dead Reckoning Part One',
    year: 2023,
    rating: 7.7,
    duration: '2h 43m',
    genres: ['Action', 'Thriller', 'Adventure'],
    poster:   { url: p('/NNxYkU70HPurnNCSiCjYAmacwm.jpg'), publicId: null },
    backdrop: { url: b('/1E5baAaEse26fej7uHcjOgEE2t2.jpg'), publicId: null },
    youtubeId: 'avz9bGMzd7M',
    synopsis: 'Ethan Hunt and his IMF team must track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands.',
    cast: ['Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 'Simon Pegg'],
    director: 'Christopher McQuarrie',
    smartLabel: 'Non-Stop Action',
  },
  {
    title: 'Free Guy',
    year: 2021,
    rating: 7.1,
    duration: '1h 55m',
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    poster:   { url: p('/xOSd6OBCQKPxQ9IVYQ7mKhDnmPH.jpg'), publicId: null },
    backdrop: { url: b('/eeijXm3553xvuFbkPFkDG6CLCbQ.jpg'), publicId: null },
    youtubeId: 'X2m-y9Yd-K4',
    synopsis: 'A bank teller discovers he is actually a background player in an open-world video game and decides to become the hero of his own story.',
    cast: ['Ryan Reynolds', 'Jodie Comer', 'Lil Rel Howery', 'Joe Keery'],
    director: 'Shawn Levy',
    smartLabel: 'Gaming Comedy',
  },
  {
    title: 'Avengers: Endgame',
    year: 2019,
    rating: 8.4,
    duration: '3h 1m',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    poster:   { url: p('/or06FN3Dka5tK1e9f14R0LpRPg4.jpg'), publicId: null },
    backdrop: { url: b('/orjiB3oUIsyz60hoEqkiGpy5CeO.jpg'), publicId: null },
    youtubeId: 'TcMBFSGVi1c',
    synopsis: 'After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos\'s actions and restore balance.',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth'],
    director: 'Anthony Russo & Joe Russo',
    smartLabel: 'Highest Grossing Film',
  },
  {
    title: 'Avengers: Infinity War',
    year: 2018,
    rating: 8.4,
    duration: '2h 29m',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    poster:   { url: p('/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg'), publicId: null },
    backdrop: { url: b('/lmZFxXgJE3vgrciwuDib0N9CfQm.jpg'), publicId: null },
    youtubeId: '6ZfuNTqbHE8',
    synopsis: 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',
    cast: ['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'Thanos'],
    director: 'Anthony Russo & Joe Russo',
    smartLabel: 'MCU Epic',
  },
  {
    title: 'Guardians of the Galaxy Vol. 3',
    year: 2023,
    rating: 8.0,
    duration: '2h 30m',
    genres: ['Action', 'Adventure', 'Comedy'],
    poster:   { url: p('/r2J02Z2OpNTctfOSN1Ydgd2xHuS.jpg'), publicId: null },
    backdrop: { url: b('/5YZbUmjbMa3ClvSohjg0ULg2jWh.jpg'), publicId: null },
    youtubeId: 'u3V5KDHRQvk',
    synopsis: 'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own.',
    cast: ['Chris Pratt', 'Zoe Saldaña', 'Dave Bautista', 'Bradley Cooper'],
    director: 'James Gunn',
    smartLabel: 'Emotional MCU Send-Off',
  },
  {
    title: 'Black Panther',
    year: 2018,
    rating: 7.3,
    duration: '2h 14m',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    poster:   { url: p('/uxzzxijgPIY7slzFvMotPv8wjKA.jpg'), publicId: null },
    backdrop: { url: b('/6ELCZlTA5lGUops70hKdB83WJxH.jpg'), publicId: null },
    youtubeId: 'xku2EA6St4I',
    synopsis: 'T\'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country\'s past.',
    cast: ['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong\'o', 'Danai Gurira'],
    director: 'Ryan Coogler',
    smartLabel: 'Cultural Phenomenon',
  },
  {
    title: 'Shang-Chi and the Legend of the Ten Rings',
    year: 2021,
    rating: 7.4,
    duration: '2h 12m',
    genres: ['Action', 'Adventure', 'Fantasy'],
    poster:   { url: p('/1BIoJGFy3oKAOFMGWKDbdNnFzeJ.jpg'), publicId: null },
    backdrop: { url: b('/eeijXm3553xvuFbkPFkDG6CLCbQ.jpg'), publicId: null },
    youtubeId: '8YjFbMbfXaQ',
    synopsis: 'Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.',
    cast: ['Simu Liu', 'Awkwafina', 'Meng\'er Zhang', 'Tony Leung Chiu-wai'],
    director: 'Destin Daniel Cretton',
    smartLabel: 'MCU Fresh Favourite',
  },
  {
    title: 'The Batman',
    year: 2022,
    rating: 7.8,
    duration: '2h 56m',
    genres: ['Action', 'Crime', 'Drama'],
    poster:   { url: p('/74xTEgt7R36Fpocon6gtnTgEAFb.jpg'), publicId: null },
    backdrop: { url: b('/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg'), publicId: null },
    youtubeId: 'mqqft2x_Aa4',
    synopsis: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption and question his family\'s involvement.',
    cast: ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano', 'Jeffrey Wright'],
    director: 'Matt Reeves',
    smartLabel: 'Dark & Gritty Reboot',
  },

  // ══════════════════════════════════════════════════════════════════
  // SCI-FI (10)
  // ══════════════════════════════════════════════════════════════════
  {
    title: 'Interstellar',
    year: 2014,
    rating: 8.7,
    duration: '2h 49m',
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    poster:   { url: p('/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'), publicId: null },
    backdrop: { url: b('/xJHokMbljvjADYdit5fK5VQsXEG.jpg'), publicId: null },
    youtubeId: 'zSWdZVtXT7E',
    synopsis: 'When Earth becomes uninhabitable in the near future, a farmer and ex-NASA pilot leads a mission through a wormhole in search of a new home for humanity.',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    director: 'Christopher Nolan',
    smartLabel: 'All-Time Classic',
  },
  {
    title: 'Dune',
    year: 2021,
    rating: 7.9,
    duration: '2h 35m',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    poster:   { url: p('/d5NXSgnueOh1K62i2H2R2fF2t2v.jpg'), publicId: null },
    backdrop: { url: b('/eSVvx8xys2NuFhl8fevXt41wX7v.jpg'), publicId: null },
    youtubeId: 'n9xhJrPXop4',
    synopsis: 'Feature adaptation of Frank Herbert\'s science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Oscar Isaac'],
    director: 'Denis Villeneuve',
    smartLabel: 'Epic Space Drama',
  },
  {
    title: 'Dune: Part Two',
    year: 2024,
    rating: 8.5,
    duration: '2h 46m',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    poster:   { url: p('/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg'), publicId: null },
    backdrop: { url: b('/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg'), publicId: null },
    youtubeId: 'Way9Dexny3w',
    synopsis: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Josh Brolin'],
    director: 'Denis Villeneuve',
    smartLabel: 'Epic Masterpiece',
  },
  {
    title: 'The Martian',
    year: 2015,
    rating: 8.0,
    duration: '2h 21m',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    poster:   { url: p('/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg'), publicId: null },
    backdrop: { url: b('/y5CgkDdRFyJo2gMG7CJhVcL8ATF.jpg'), publicId: null },
    youtubeId: 'ej3ioOneTy8',
    synopsis: 'An astronaut becomes stranded on Mars after his team assumes him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.',
    cast: ['Matt Damon', 'Jessica Chastain', 'Kristen Wiig', 'Jeff Daniels'],
    director: 'Ridley Scott',
    smartLabel: 'Optimistic Survival',
  },
  {
    title: 'Everything Everywhere All at Once',
    year: 2022,
    rating: 7.8,
    duration: '2h 19m',
    genres: ['Sci-Fi', 'Comedy', 'Drama'],
    poster:   { url: p('/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg'), publicId: null },
    backdrop: { url: b('/u6nCjagS9zDfPiRWJQmONMvJFvQ.jpg'), publicId: null },
    youtubeId: 'wxN1T1uxQ2g',
    synopsis: 'An aging Chinese immigrant is swept up in an insane adventure where she alone can save the world by exploring other universes.',
    cast: ['Michelle Yeoh', 'Ke Huy Quan', 'Jamie Lee Curtis', 'Stephanie Hsu'],
    director: 'Daniel Kwan & Daniel Scheinert',
    smartLabel: 'Mind-Bending',
  },
  {
    title: 'Ready Player One',
    year: 2018,
    rating: 7.4,
    duration: '2h 20m',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    poster:   { url: p('/pU1UecAcGEcjv61oNk5j5yFE4o.jpg'), publicId: null },
    backdrop: { url: b('/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg'), publicId: null },
    youtubeId: 'cSp1dM2Vj48',
    synopsis: 'When the creator of a virtual reality world called the OASIS dies, he releases a video in which he challenges all OASIS users to find his Easter Egg.',
    cast: ['Tye Sheridan', 'Olivia Cooke', 'Ben Mendelsohn', 'Lena Waithe'],
    director: 'Steven Spielberg',
    smartLabel: 'Cyber Adventure',
  },
  {
    title: 'Kingdom of the Planet of the Apes',
    year: 2024,
    rating: 7.1,
    duration: '2h 25m',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    poster:   { url: p('/gKkl37BQuKTanygYQG1pyYgLVgf.jpg'), publicId: null },
    backdrop: { url: b('/fqv8v6AycXKsivp1T5yKtLbGXce.jpg'), publicId: null },
    youtubeId: 'XnOqbeXMOj4',
    synopsis: 'Many years after the reign of Caesar, a young ape embarks on a journey that leads him to question everything he was taught about the past.',
    cast: ['Owen Teague', 'Freya Allan', 'Kevin Durand', 'Peter Macon'],
    director: 'Wes Ball',
    smartLabel: 'Sci-Fi Epic',
  },
  {
    title: 'Arrival',
    year: 2016,
    rating: 7.9,
    duration: '1h 56m',
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    poster:   { url: p('/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg'), publicId: null },
    backdrop: { url: b('/bumflR8VerNf9oLCGMEHBkMNzJT.jpg'), publicId: null },
    youtubeId: 'tFMo3UJ4B4g',
    synopsis: 'A linguist is recruited by the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
    cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker', 'Michael Stuhlbarg'],
    director: 'Denis Villeneuve',
    smartLabel: 'Cerebral Sci-Fi',
  },
  {
    title: 'Ad Astra',
    year: 2019,
    rating: 6.5,
    duration: '2h 3m',
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    poster:   { url: p('/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg'), publicId: null },
    backdrop: { url: b('/5BwqwxMEjeFtdknRV792Svo0K1v.jpg'), publicId: null },
    youtubeId: 'EqRb_RYy5CE',
    synopsis: 'Astronaut Roy McBride travels to the outer edges of the solar system to find his missing father and unravel a mystery that threatens the survival of Earth.',
    cast: ['Brad Pitt', 'Tommy Lee Jones', 'Ruth Negga', 'Liv Tyler'],
    director: 'James Gray',
    smartLabel: 'Introspective Space Drama',
  },
  {
    title: 'Tenet',
    year: 2020,
    rating: 7.3,
    duration: '2h 30m',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    poster:   { url: p('/6HbkKPnMNkQ1j9GKBEqoSCQmrAE.jpg'), publicId: null },
    backdrop: { url: b('/wzJRB4MKi1yJoqBloBzhkwY65G.jpg'), publicId: null },
    youtubeId: 'LdOM0x0xdwM',
    synopsis: 'Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage.',
    cast: ['John David Washington', 'Robert Pattinson', 'Elizabeth Debicki', 'Kenneth Branagh'],
    director: 'Christopher Nolan',
    smartLabel: 'Mind-Bending Espionage',
  },

  // ══════════════════════════════════════════════════════════════════
  // DRAMA (10)
  // ══════════════════════════════════════════════════════════════════
  {
    title: 'Oppenheimer',
    year: 2023,
    rating: 8.3,
    duration: '3h 0m',
    genres: ['Drama', 'History', 'Biography'],
    poster:   { url: p('/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'), publicId: null },
    backdrop: { url: b('/rLb2cwF3Myh1gWrSDeRSBsxhMeC.jpg'), publicId: null },
    youtubeId: 'uYPbbksJxIg',
    synopsis: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    director: 'Christopher Nolan',
    smartLabel: 'Award-Winning',
  },
  {
    title: 'The Holdovers',
    year: 2023,
    rating: 8.0,
    duration: '2h 13m',
    genres: ['Drama', 'Comedy'],
    poster:   { url: p('/VHmCMFkDsGRlCCBgjAmzaTm0gw.jpg'), publicId: null },
    backdrop: { url: b('/hGK2m5CVNEW5GCwbKYEEIXjFkHh.jpg'), publicId: null },
    youtubeId: 'AhKEnFfMoHQ',
    synopsis: 'A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break to look after a handful of students with nowhere to go.',
    cast: ['Paul Giamatti', 'Dominic Sessa', 'Da\'Vine Joy Randolph', 'Carrie Preston'],
    director: 'Alexander Payne',
    smartLabel: 'Hidden Gem',
  },
  {
    title: 'Barbie',
    year: 2023,
    rating: 6.9,
    duration: '1h 54m',
    genres: ['Drama', 'Comedy', 'Fantasy'],
    poster:   { url: p('/iuFNMS8vlzmXFj3jqnWpxIQwDDb.jpg'), publicId: null },
    backdrop: { url: b('/nHf61UzkfFno5X1ofIjuPJuc21e.jpg'), publicId: null },
    youtubeId: 'pBk4NYhaPos',
    synopsis: 'Barbie suffers a crisis that leads her to question her world and her existence. She and Ken go on a journey of self-discovery in the real world.',
    cast: ['Margot Robbie', 'Ryan Gosling', 'America Ferrera', 'Kate McKinnon'],
    director: 'Greta Gerwig',
    smartLabel: 'Cultural Phenomenon',
  },
  {
    title: 'Ford v Ferrari',
    year: 2019,
    rating: 8.1,
    duration: '2h 32m',
    genres: ['Drama', 'Action', 'Biography'],
    poster:   { url: p('/deGq7tL2oBf44jZ5R1oUaK1L1xW.jpg'), publicId: null },
    backdrop: { url: b('/6Y21Vj34L94H8s25N1oUaK1L1xW.jpg'), publicId: null },
    youtubeId: 'I3h95Fs9KB8',
    synopsis: 'American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford.',
    cast: ['Matt Damon', 'Christian Bale', 'Jon Bernthal', 'Caitriona Balfe'],
    director: 'James Mangold',
    smartLabel: 'Highly Inspiring',
  },
  {
    title: 'The Fabelmans',
    year: 2022,
    rating: 7.6,
    duration: '2h 31m',
    genres: ['Drama', 'Biography'],
    poster:   { url: p('/SnOALOeK25R6KtT5ZNOI3PKOPWH.jpg'), publicId: null },
    backdrop: { url: b('/hQNOk1LzR5AkADFJ5SkFq5gWwx.jpg'), publicId: null },
    youtubeId: 'D1G2i5_52pA',
    synopsis: 'Growing up in post-World War II era, young Sammy Fabelman aspires to become a filmmaker, but soon discovers a shattering family secret.',
    cast: ['Gabriel LaBelle', 'Michelle Williams', 'Paul Dano', 'Seth Rogen'],
    director: 'Steven Spielberg',
    smartLabel: 'Autobiographical Drama',
  },
  {
    title: 'A Beautiful Day in the Neighborhood',
    year: 2019,
    rating: 7.2,
    duration: '1h 49m',
    genres: ['Drama', 'Biography'],
    poster:   { url: p('/3bqRmcTl4WONjV5xKHFEzjb7EHU.jpg'), publicId: null },
    backdrop: { url: b('/j9c32aDcbvP7LVuGm94t5c6WQJB.jpg'), publicId: null },
    youtubeId: '-VYEgpRLmPo',
    synopsis: 'Based on the true story of a real-life friendship between Fred Rogers and journalist Lloyd Vogel.',
    cast: ['Tom Hanks', 'Matthew Rhys', 'Susan Kelechi Watson', 'Chris Cooper'],
    director: 'Marielle Heller',
    smartLabel: 'Deeply Moving',
  },
  {
    title: 'Green Book',
    year: 2018,
    rating: 8.2,
    duration: '2h 10m',
    genres: ['Drama', 'Comedy', 'Biography'],
    poster:   { url: p('/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg'), publicId: null },
    backdrop: { url: b('/cBz9rEMEarA9YJnUDiNbJWMSfQ9.jpg'), publicId: null },
    youtubeId: 'QkZoJdUuVwY',
    synopsis: 'A working-class Italian-American bouncer becomes the driver of an African-American classical pianist on a venue tour through the 1960s American South.',
    cast: ['Viggo Mortensen', 'Mahershala Ali', 'Linda Cardellini', 'Sebastian Maniscalco'],
    director: 'Peter Farrelly',
    smartLabel: 'Academy Award Winner',
  },
  {
    title: 'Hidden Figures',
    year: 2016,
    rating: 7.8,
    duration: '2h 7m',
    genres: ['Drama', 'History', 'Biography'],
    poster:   { url: p('/yPisjyLweCl1tbgwgtzBCNCBle.jpg'), publicId: null },
    backdrop: { url: b('/m8tMNiKlrW6hK3JI8yKNPEsJEjM.jpg'), publicId: null },
    youtubeId: '5wfrDhgUMGI',
    synopsis: 'The story of a team of female African-American mathematicians who served a vital role in NASA during the early years of the U.S. space program.',
    cast: ['Taraji P. Henson', 'Octavia Spencer', 'Janelle Monáe', 'Kevin Costner'],
    director: 'Theodore Melfi',
    smartLabel: 'Powerful Truth',
  },
  {
    title: 'The Pursuit of Happyness',
    year: 2006,
    rating: 8.0,
    duration: '1h 57m',
    genres: ['Drama', 'Biography'],
    poster:   { url: p('/lBpPlalb1W6tBnKODNjORqoxHZ.jpg'), publicId: null },
    backdrop: { url: b('/4f3ERLzwDkVaF4VLEkIkVa8RuNI.jpg'), publicId: null },
    youtubeId: 'DMOBlEGMne4',
    synopsis: 'A struggling salesman takes custody of his son as he\'s on the brink of homelessness. Based on the true story of Chris Gardner.',
    cast: ['Will Smith', 'Jaden Smith', 'Thandiwe Newton', 'Brian Howe'],
    director: 'Gabriele Muccino',
    smartLabel: 'Iconic Motivational',
  },
  {
    title: 'Gifted',
    year: 2017,
    rating: 7.6,
    duration: '1h 41m',
    genres: ['Drama', 'Family'],
    poster:   { url: p('/5dS9Y2ezOhTiZJVsPf3bPbExOiX.jpg'), publicId: null },
    backdrop: { url: b('/gCuGQNEoqpwdBLqGz8k3d8zy3YQ.jpg'), publicId: null },
    youtubeId: 'lKGqAfRbKFo',
    synopsis: 'Frank, a single man raising his child prodigy niece Mary, is drawn into a custody battle with his own mother.',
    cast: ['Chris Evans', 'Mckenna Grace', 'Lindsay Duncan', 'Jenny Slate'],
    director: 'Marc Webb',
    smartLabel: 'Heartfelt Drama',
  },

  // ══════════════════════════════════════════════════════════════════
  // FANTASY (10) — includes RRR (Indian)
  // ══════════════════════════════════════════════════════════════════
  {
    title: 'Wicked',
    year: 2024,
    rating: 7.7,
    duration: '2h 40m',
    genres: ['Fantasy', 'Musical', 'Drama'],
    poster:   { url: p('/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg'), publicId: null },
    backdrop: { url: b('/uKb22E0nlzr914bA9KyA5CVCOlV.jpg'), publicId: null },
    youtubeId: 'vt98AlBDI9Y',
    synopsis: 'The story of the unlikely friendship between Elphaba and Glinda in the land of Oz, before Dorothy ever arrived.',
    cast: ['Cynthia Erivo', 'Ariana Grande', 'Jeff Goldblum', 'Jonathan Bailey'],
    director: 'Jon M. Chu',
    smartLabel: 'Spectacular Musical',
  },
  {
    title: 'Doctor Strange',
    year: 2016,
    rating: 7.5,
    duration: '1h 55m',
    genres: ['Fantasy', 'Action', 'Adventure'],
    poster:   { url: p('/4PiiZFCijdEjRmaEB6tkzsE8HNH.jpg'), publicId: null },
    backdrop: { url: b('/qoqRdGKfotTmQcmTVyC9kSrUCJN.jpg'), publicId: null },
    youtubeId: 'HSzx-zryEgM',
    synopsis: 'After his career is destroyed, a brilliant but arrogant surgeon gets a new perspective through a journey into the world of the mystic arts.',
    cast: ['Benedict Cumberbatch', 'Chiwetel Ejiofor', 'Rachel McAdams', 'Tilda Swinton'],
    director: 'Scott Derrickson',
    smartLabel: 'MCU Mystic Adventure',
  },
  {
    title: 'Doctor Strange in the Multiverse of Madness',
    year: 2022,
    rating: 6.9,
    duration: '2h 6m',
    genres: ['Fantasy', 'Action', 'Horror'],
    poster:   { url: p('/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg'), publicId: null },
    backdrop: { url: b('/oqOXXkFCPdv0JZcJRpCWp7wPBbV.jpg'), publicId: null },
    youtubeId: 'aWzlQ2N6qqg',
    synopsis: 'Doctor Strange teams with a mysterious new ally to face a powerful enemy bent on destroying him. But when their mission goes wrong, Strange must travel into the multiverse.',
    cast: ['Benedict Cumberbatch', 'Elizabeth Olsen', 'Chiwetel Ejiofor', 'Benedict Wong'],
    director: 'Sam Raimi',
    smartLabel: 'Multiverse Madness',
  },
  {
    title: 'Fantastic Beasts and Where to Find Them',
    year: 2016,
    rating: 7.3,
    duration: '2h 12m',
    genres: ['Fantasy', 'Adventure', 'Family'],
    poster:   { url: p('/gNn9SB0mYQaePaXFdOGwGQ78UEv.jpg'), publicId: null },
    backdrop: { url: b('/nbs0RJMcJsqIbsHXCnzKlm3RiJb.jpg'), publicId: null },
    youtubeId: '1bqYZGcJAlQ',
    synopsis: 'The adventures of writer Newt Scamander in New York\'s secret community of witches and wizards, seventy years before Harry Potter reads his book in school.',
    cast: ['Eddie Redmayne', 'Katherine Waterston', 'Alison Sudol', 'Dan Fogler'],
    director: 'David Yates',
    smartLabel: 'Wizarding World',
  },
  {
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    year: 2018,
    rating: 6.5,
    duration: '2h 14m',
    genres: ['Fantasy', 'Adventure', 'Drama'],
    poster:   { url: p('/rBX4nDMTEjBPCBJHiqPjkv9AQHJ.jpg'), publicId: null },
    backdrop: { url: b('/wgEVFBGqUwNsITXzN4mG15JWKRQ.jpg'), publicId: null },
    youtubeId: '2s0rIwG72EI',
    synopsis: 'The second adventure in the Wizarding World, with Gellert Grindelwald having escaped custody and begun gathering followers.',
    cast: ['Eddie Redmayne', 'Jude Law', 'Ezra Miller', 'Zoe Kravitz'],
    director: 'David Yates',
    smartLabel: 'Wizarding Sequel',
  },
  {
    title: 'The Hobbit: An Unexpected Journey',
    year: 2012,
    rating: 7.8,
    duration: '2h 49m',
    genres: ['Fantasy', 'Adventure', 'Drama'],
    poster:   { url: p('/vIgu2NJXEbKDNK7TlZQa5WjuAYf.jpg'), publicId: null },
    backdrop: { url: b('/hJuDvwISdJkVF6sHzGrSCgqlWY5.jpg'), publicId: null },
    youtubeId: 'SDnYMbYB-nU',
    synopsis: 'A reluctant Hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home, and the help of the wizard Gandalf.',
    cast: ['Martin Freeman', 'Ian McKellen', 'Richard Armitage', 'Andy Serkis'],
    director: 'Peter Jackson',
    smartLabel: 'Epic Fantasy',
  },
  {
    title: 'The Hobbit: The Desolation of Smaug',
    year: 2013,
    rating: 7.8,
    duration: '2h 41m',
    genres: ['Fantasy', 'Adventure', 'Action'],
    poster:   { url: p('/xSL8A8Uf9UL6Q16E0e6J3HbeJzl.jpg'), publicId: null },
    backdrop: { url: b('/j3Z3XktmWB1VhsS8iXNcrR86PXi.jpg'), publicId: null },
    youtubeId: 'ZRbdXZiRZrM',
    synopsis: 'The Dwarves, Bilbo and Gandalf have successfully escaped the Misty Mountains, and Bilbo has gained the One Ring. They all continue their journey to Lonely Mountain.',
    cast: ['Martin Freeman', 'Ian McKellen', 'Richard Armitage', 'Benedict Cumberbatch'],
    director: 'Peter Jackson',
    smartLabel: 'Dragon Encounter',
  },
  {
    title: 'The Hobbit: The Battle of the Five Armies',
    year: 2014,
    rating: 7.4,
    duration: '2h 24m',
    genres: ['Fantasy', 'Adventure', 'Action'],
    poster:   { url: p('/kBgfCBXOiNsEWjqNKkMpFtEHZtg.jpg'), publicId: null },
    backdrop: { url: b('/6UlFRGJ8oicnPH2D3gqtC4c5V9W.jpg'), publicId: null },
    youtubeId: 'iVAgTiBrrDA',
    synopsis: 'Bilbo and company are forced to engage in a war against an array of combatants and keep the Lonely Mountain from falling into the hands of a rising darkness.',
    cast: ['Martin Freeman', 'Ian McKellen', 'Richard Armitage', 'Evangeline Lilly'],
    director: 'Peter Jackson',
    smartLabel: 'Epic Finale',
  },
  {
    title: 'Harry Potter and the Deathly Hallows Part 2',
    year: 2011,
    rating: 8.1,
    duration: '2h 10m',
    genres: ['Fantasy', 'Adventure', 'Drama'],
    poster:   { url: p('/3a6FEfhBxXnNgapaRePOWB9VZMK.jpg'), publicId: null },
    backdrop: { url: b('/o1TBnEsNoLkuXhk5A6bPVDMOoiH.jpg'), publicId: null },
    youtubeId: 'mObK5XD8udk',
    synopsis: 'Harry, Ron and Hermione search for Voldemort\'s remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.',
    cast: ['Daniel Radcliffe', 'Emma Watson', 'Rupert Grint', 'Ralph Fiennes'],
    director: 'David Yates',
    smartLabel: 'Iconic Series Finale',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'RRR',
    year: 2022,
    rating: 8.0,
    duration: '3h 7m',
    genres: ['Fantasy', 'Action', 'Drama'],
    poster:   { url: p('/nEufeZlyAOLqO2brrs0yeF1lgXO.jpg'), publicId: null },
    backdrop: { url: b('/9bXDEOBsLIBGBRrGioOVsNECgpR.jpg'), publicId: null },
    youtubeId: 'f_vbVVH9M2c',
    synopsis: 'A fictional story about two legendary freedom fighters who chose the path of rebellion against the British Empire in the 1920s.',
    cast: ['N. T. Rama Rao Jr.', 'Ram Charan', 'Alia Bhatt', 'Ajay Devgn'],
    director: 'S. S. Rajamouli',
    smartLabel: '🇮🇳 Indian Blockbuster',
  },

  // ══════════════════════════════════════════════════════════════════
  // MYSTERY (10) — includes Drishyam 2 (Indian)
  // ══════════════════════════════════════════════════════════════════
  {
    title: 'Glass Onion: A Knives Out Mystery',
    year: 2022,
    rating: 7.1,
    duration: '2h 19m',
    genres: ['Mystery', 'Comedy', 'Thriller'],
    poster:   { url: p('/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg'), publicId: null },
    backdrop: { url: b('/dRLSoufWtc16JPKoy9fPDRQNASI.jpg'), publicId: null },
    youtubeId: 'CRCifcJ4Uqg',
    synopsis: 'Detective Benoit Blanc travels to Greece to unravel the layers of a mystery surrounding a tech billionaire and his carefully curated group of friends.',
    cast: ['Daniel Craig', 'Edward Norton', 'Janelle Monáe', 'Kate Hudson'],
    director: 'Rian Johnson',
    smartLabel: 'Whodunit Delight',
  },
  {
    title: 'Knives Out',
    year: 2019,
    rating: 7.9,
    duration: '2h 10m',
    genres: ['Mystery', 'Comedy', 'Drama'],
    poster:   { url: p('/pThyQovXQrpS2AR1G3TkEFAv9aD.jpg'), publicId: null },
    backdrop: { url: b('/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg'), publicId: null },
    youtubeId: 'qGqiHJTsRkQ',
    synopsis: 'A detective investigates the death of a patriarch of an eccentric, combative family.',
    cast: ['Daniel Craig', 'Chris Evans', 'Ana de Armas', 'Jamie Lee Curtis'],
    director: 'Rian Johnson',
    smartLabel: 'Modern Whodunit',
  },
  {
    title: 'Sherlock Holmes',
    year: 2009,
    rating: 7.6,
    duration: '2h 8m',
    genres: ['Mystery', 'Action', 'Adventure'],
    poster:   { url: p('/qOTca3PhoSBLfuVvOhFiTfqnLHx.jpg'), publicId: null },
    backdrop: { url: b('/mKXi1fStJfFe3cIHdBYolCCRaSD.jpg'), publicId: null },
    youtubeId: 'VomFGrNqvtc',
    synopsis: 'Detective Sherlock Holmes and his stalwart partner Watson engage in a battle of wits and brawn with a nemesis whose plot is a threat to all of England.',
    cast: ['Robert Downey Jr.', 'Jude Law', 'Rachel McAdams', 'Mark Strong'],
    director: 'Guy Ritchie',
    smartLabel: 'Guy Ritchie Action',
  },
  {
    title: 'Sherlock Holmes: A Game of Shadows',
    year: 2011,
    rating: 7.4,
    duration: '2h 9m',
    genres: ['Mystery', 'Action', 'Adventure'],
    poster:   { url: p('/Ar7CPGgVMQDiUd8meU4SlBW3EHG.jpg'), publicId: null },
    backdrop: { url: b('/hPkcoFhWKcTCiLSvtjQ7dMH8F0.jpg'), publicId: null },
    youtubeId: 'V17zXw8u1F4',
    synopsis: 'Sherlock Holmes and his sidekick Watson join forces to outwit and bring down their fiercest adversary, Professor Moriarty.',
    cast: ['Robert Downey Jr.', 'Jude Law', 'Jared Harris', 'Noomi Rapace'],
    director: 'Guy Ritchie',
    smartLabel: 'Action Mystery',
  },
  {
    title: 'Enola Holmes',
    year: 2020,
    rating: 6.6,
    duration: '2h 3m',
    genres: ['Mystery', 'Adventure', 'Drama'],
    poster:   { url: p('/riYInlsq2kf1AWoGm80JQW5dLKp.jpg'), publicId: null },
    backdrop: { url: b('/x6Dv0Hb3hMxJhh5j41Qg8W10gEe.jpg'), publicId: null },
    youtubeId: '1d0KphvXhA8',
    synopsis: 'When her mother disappears, Sherlock Holmes\' sister Enola goes on a mission to find her, becoming a detective in her own right.',
    cast: ['Millie Bobby Brown', 'Henry Cavill', 'Sam Claflin', 'Helena Bonham Carter'],
    director: 'Harry Bradbeer',
    smartLabel: 'Teen Detective',
  },
  {
    title: 'Enola Holmes 2',
    year: 2022,
    rating: 6.7,
    duration: '2h 9m',
    genres: ['Mystery', 'Adventure', 'Drama'],
    poster:   { url: p('/tVh0eMfXnq9XkHMF0YFHm2okzLi.jpg'), publicId: null },
    backdrop: { url: b('/qZ4mcWTe4SuXbZmKWNqWBFiIqVy.jpg'), publicId: null },
    youtubeId: 'KKXegJFeJGo',
    synopsis: 'Now a detective-for-hire, Enola Holmes takes on her first official case to find a missing girl, as the sparks of a dangerous conspiracy ignite.',
    cast: ['Millie Bobby Brown', 'Henry Cavill', 'David Thewlis', 'Louis Partridge'],
    director: 'Harry Bradbeer',
    smartLabel: 'High Stakes Sequel',
  },
  {
    title: 'Murder on the Orient Express',
    year: 2017,
    rating: 6.7,
    duration: '1h 51m',
    genres: ['Mystery', 'Drama', 'Crime'],
    poster:   { url: p('/tdBuqBuvRsGIlDDUQUdE3OKNeNx.jpg'), publicId: null },
    backdrop: { url: b('/oLIZOKM2bFUGLqWvZbqcH3r9EFB.jpg'), publicId: null },
    youtubeId: 'Mq4m3yAoW8E',
    synopsis: 'When a murder occurs on the train he\'s travelling, celebrated detective Hercule Poirot is recruited to solve the case.',
    cast: ['Kenneth Branagh', 'Penélope Cruz', 'Willem Dafoe', 'Judi Dench'],
    director: 'Kenneth Branagh',
    smartLabel: 'Classic Murder Mystery',
  },
  {
    title: 'Death on the Nile',
    year: 2022,
    rating: 6.3,
    duration: '2h 7m',
    genres: ['Mystery', 'Drama', 'Crime'],
    poster:   { url: p('/jD4MvkMFnMNFAIu9cNKNSGUy3Nm.jpg'), publicId: null },
    backdrop: { url: b('/b64E6vdXgNnOJ6VzDqvmajqFgUq.jpg'), publicId: null },
    youtubeId: 'dZRqB0cOD-A',
    synopsis: 'While on vacation on the Nile, Hercule Poirot must investigate the murder of a young heiress.',
    cast: ['Kenneth Branagh', 'Gal Gadot', 'Armie Hammer', 'Emma Mackey'],
    director: 'Kenneth Branagh',
    smartLabel: 'Agatha Christie Tale',
  },
  {
    title: 'See How They Run',
    year: 2022,
    rating: 6.5,
    duration: '1h 38m',
    genres: ['Mystery', 'Comedy', 'Crime'],
    poster:   { url: p('/7fEHBoJH08wJCNM8uNHEo4ToqKM.jpg'), publicId: null },
    backdrop: { url: b('/yZ1m8b9XkNOqjMGEHVCaWCdG8IN.jpg'), publicId: null },
    youtubeId: 'O7GKUBLqMJM',
    synopsis: 'In the West End of 1950s London, plans for a movie version of a smash-hit play are stopped short when a member of the crew is murdered.',
    cast: ['Sam Rockwell', 'Saoirse Ronan', 'Adrien Brody', 'Ruth Wilson'],
    director: 'Tom George',
    smartLabel: 'Whodunit Comedy',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'Drishyam 2',
    year: 2022,
    rating: 8.3,
    duration: '2h 32m',
    genres: ['Mystery', 'Drama', 'Crime'],
    poster:   { url: p('/BcI6s50SuTBKhVUJyinpUJJlnf8.jpg'), publicId: null },
    backdrop: { url: b('/qBvGCJUDAHqRzSnuqzMCXJfYgBo.jpg'), publicId: null },
    youtubeId: 'iBl4CbfqGYQ',
    synopsis: 'Seven years after the events of the first film, Vijay Salgaonkar struggles to move on. But the past threatens to catch up with him in unexpected ways.',
    cast: ['Ajay Devgn', 'Tabu', 'Shriya Saran', 'Akshaye Khanna'],
    director: 'Abhishek Pathak',
    smartLabel: '🇮🇳 Desi Thriller',
  },

  // ══════════════════════════════════════════════════════════════════
  // THRILLER (10) — includes KGF 2 and Baahubali 2 (Indian)
  // ══════════════════════════════════════════════════════════════════
  {
    title: 'Twisters',
    year: 2024,
    rating: 7.2,
    duration: '2h 2m',
    genres: ['Thriller', 'Action', 'Adventure'],
    poster:   { url: p('/pjnD08NmLEhuaf29S664Zl5Y8Jb.jpg'), publicId: null },
    backdrop: { url: b('/7LGkNhBQMkE9tBJFhSJK4pGOKPi.jpg'), publicId: null },
    youtubeId: 'aHEgtXhOQRQ',
    synopsis: 'Storm chasers race across the Great Plains to test a new system that could neutralize the destructive power of tornadoes, while competing agendas put everyone at risk.',
    cast: ['Daisy Edgar-Jones', 'Glen Powell', 'Anthony Ramos', 'Maura Tierney'],
    director: 'Lee Isaac Chung',
    smartLabel: 'Edge of Your Seat',
  },
  {
    title: 'Mission: Impossible – Fallout',
    year: 2018,
    rating: 7.7,
    duration: '2h 27m',
    genres: ['Action', 'Thriller', 'Adventure'],
    poster:   { url: p('/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg'), publicId: null },
    backdrop: { url: b('/5qxePyMYDisSE2MNhHoRRk6GUYA.jpg'), publicId: null },
    youtubeId: 'wb49-oV0F78',
    synopsis: 'Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.',
    cast: ['Tom Cruise', 'Henry Cavill', 'Ving Rhames', 'Simon Pegg'],
    director: 'Christopher McQuarrie',
    smartLabel: 'Best Action Sequel',
  },
  {
    title: 'Bullet Train',
    year: 2022,
    rating: 7.3,
    duration: '2h 6m',
    genres: ['Action', 'Thriller', 'Comedy'],
    poster:   { url: p('/j8szC8OgrejDdBbcPHOHBZ2G5m1.jpg'), publicId: null },
    backdrop: { url: b('/bDj4jXGNyxNYs4xaEJuELi1vvdX.jpg'), publicId: null },
    youtubeId: '0IOsk2Vlc4o',
    synopsis: 'Five assassins aboard a fast-moving bullet train find out their missions have something in common.',
    cast: ['Brad Pitt', 'Joey King', 'Aaron Taylor-Johnson', 'Brian Tyree Henry'],
    director: 'David Leitch',
    smartLabel: 'Stylish Action',
  },
  {
    title: 'Extraction',
    year: 2020,
    rating: 6.7,
    duration: '1h 56m',
    genres: ['Action', 'Thriller'],
    poster:   { url: p('/1R6cvRtZgsYCkh8UFuWHj5omB.jpg'), publicId: null },
    backdrop: { url: b('/3XkRSfasETLUaOMFBSECMG3TA7G.jpg'), publicId: null },
    youtubeId: 'L4DrolmDxmw',
    synopsis: 'A hardened mercenary\'s mission becomes a soul-searching race to survive when he\'s sent into Bangladesh to rescue a drug lord\'s kidnapped son.',
    cast: ['Chris Hemsworth', 'Rudhraksh Jaiswal', 'Randeep Hooda', 'Golshifteh Farahani'],
    director: 'Sam Hargrave',
    smartLabel: 'High Octane Action',
  },
  {
    title: 'Extraction 2',
    year: 2023,
    rating: 7.0,
    duration: '2h 2m',
    genres: ['Action', 'Thriller'],
    poster:   { url: p('/7GpxXMOaFz3pqeOC4c1UbhcWBiF.jpg'), publicId: null },
    backdrop: { url: b('/5aV8s9MRmotMtqkrZV0OkniFzJA.jpg'), publicId: null },
    youtubeId: 'Y274jZs5s7s',
    synopsis: 'Tyler Rake is back, and after barely surviving his previous mission, he must face the deadly new villain Alcott.',
    cast: ['Chris Hemsworth', 'Golshifteh Farahani', 'Adam Bessa', 'Olga Kurylenko'],
    director: 'Sam Hargrave',
    smartLabel: 'Action Sequel',
  },
  {
    title: 'Plane',
    year: 2023,
    rating: 6.7,
    duration: '1h 47m',
    genres: ['Action', 'Thriller'],
    poster:   { url: p('/qi9ObTOOhiHkFVTsJSXT9WVcP1.jpg'), publicId: null },
    backdrop: { url: b('/mPzDqQ6Yn8hnT7kKcXnKJBKpyiC.jpg'), publicId: null },
    youtubeId: 'PzMfHhWFxjA',
    synopsis: 'Pilot Brodie Torrance saves his passengers from a lightning strike by making a risky landing on a war-torn island, only to find that surviving the landing was just the beginning.',
    cast: ['Gerard Butler', 'Mike Colter', 'Yoson An', 'Paul Ben-Victor'],
    director: 'Jean-François Richet',
    smartLabel: 'High-Tension Survival',
  },
  {
    title: 'Gran Turismo',
    year: 2023,
    rating: 7.3,
    duration: '2h 14m',
    genres: ['Action', 'Drama', 'Thriller'],
    poster:   { url: p('/51tqzRtKMMZEYUpSYkIy2a5Z5gr.jpg'), publicId: null },
    backdrop: { url: b('/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg'), publicId: null },
    youtubeId: 'bOFXpMbkiUE',
    synopsis: 'The incredible true story of Jann Mardenborough, a teenage gamer whose extraordinary skill at Gran Turismo earned him a chance to become a professional race car driver.',
    cast: ['Archie Madekwe', 'David Harbour', 'Orlando Bloom', 'Djimon Hounsou'],
    director: 'Neill Blomkamp',
    smartLabel: 'Inspiring True Story',
  },
  {
    title: 'The Gray Man',
    year: 2022,
    rating: 6.5,
    duration: '2h 2m',
    genres: ['Action', 'Thriller'],
    poster:   { url: p('/8Er3JgCFI8GS2tBJBuOgCMBHDU8.jpg'), publicId: null },
    backdrop: { url: b('/3Ch7VNYOwHkpKjFB0F4bOCzKKZ3.jpg'), publicId: null },
    youtubeId: 'pIgQWVWbK8I',
    synopsis: 'CIA operative Court Gentry, aka Sierra Six, is extracted from a federal prison and recruited by his handler, Donald Fitzroy. Years later, Six is a highly-skilled asset.',
    cast: ['Ryan Gosling', 'Chris Evans', 'Ana de Armas', 'Jessica Henwick'],
    director: 'Anthony Russo & Joe Russo',
    smartLabel: 'Global Action Thriller',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'KGF: Chapter 2',
    year: 2022,
    rating: 8.2,
    duration: '2h 48m',
    genres: ['Action', 'Thriller', 'Drama'],
    poster:   { url: p('/dQeAar5A13b3x37pS1753nBw7tE.jpg'), publicId: null },
    backdrop: { url: b('/8lmIHqmBMGVJGKUvKZgq4jgw8xK.jpg'), publicId: null },
    youtubeId: 'WiyF77p-dZk',
    synopsis: 'Rocky is now in command of Narachi and is feared by his enemies. His rule over the gold mine is challenged by Adheera and a vengeful politician.',
    cast: ['Yash', 'Sanjay Dutt', 'Raveena Tandon', 'Srinidhi Shetty'],
    director: 'Prashanth Neel',
    smartLabel: '🇮🇳 Pan-India Blockbuster',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'Baahubali 2: The Conclusion',
    year: 2017,
    rating: 8.4,
    duration: '2h 47m',
    genres: ['Action', 'Drama', 'Fantasy'],
    poster:   { url: p('/k68nPUPQU69Y89rM4N8g0t6l9uX.jpg'), publicId: null },
    backdrop: { url: b('/y31XYGk5T9M396zO3g4v4vGk6yq.jpg'), publicId: null },
    youtubeId: 'G38PuFJkbS8',
    synopsis: 'When Shiva, the son of Baahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.',
    cast: ['Prabhas', 'Rana Daggubati', 'Anushka Shetty', 'Tamannaah Bhatia'],
    director: 'S. S. Rajamouli',
    smartLabel: '🇮🇳 Highest Grossing Indian Film',
  },

  // ══════════════════════════════════════════════════════════════════
  // INDIAN CINEMA EXPANSION 🇮🇳 (8 additions — total Indian: 12)
  // ══════════════════════════════════════════════════════════════════
  {
    // INDIAN CINEMA 🇮🇳
    title: 'Dangal',
    year: 2016,
    rating: 8.3,
    duration: '2h 41m',
    genres: ['Drama', 'Biography', 'Action'],
    poster:   { url: p('/p2lVAcPuRPSO8Al6hDDGw0OgMi8.jpg'), publicId: null },
    backdrop: { url: b('/3hBYQJ2d5P3KzYHAjgB6GO44p6p.jpg'), publicId: null },
    youtubeId: 'x_7YlGv9u1g',
    synopsis: 'Former wrestler Mahavir Singh Phogat trains his daughters Geeta and Babita to become world-class wrestlers, challenging societal norms in rural India.',
    cast: ['Aamir Khan', 'Fatima Sana Shaikh', 'Sanya Malhotra', 'Zaira Wasim'],
    director: 'Nitesh Tiwari',
    smartLabel: '🇮🇳 Inspirational Masterpiece',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'Pathaan',
    year: 2023,
    rating: 5.8,
    duration: '2h 26m',
    genres: ['Action', 'Thriller'],
    poster:   { url: p('/tTf1Z3f93FzY10FwV8x5528o81G.jpg'), publicId: null },
    backdrop: { url: b('/35z8ut2ZzY5tT94n2Wc12z66P2s.jpg'), publicId: null },
    youtubeId: 'vqu4z34wENw',
    synopsis: 'An imprisoned spy returns to action when India faces its greatest threat — a rogue agent with a deadly weapon and a personal vendetta.',
    cast: ['Shah Rukh Khan', 'Deepika Padukone', 'John Abraham', 'Dimple Kapadia'],
    director: 'Siddharth Anand',
    smartLabel: '🇮🇳 SRK Returns',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'Jawan',
    year: 2023,
    rating: 6.9,
    duration: '2h 49m',
    genres: ['Action', 'Drama', 'Thriller'],
    poster:   { url: p('/klnS32Y2VqH6B4m4y199J536jLw.jpg'), publicId: null },
    backdrop: { url: b('/jXY1e81EHs1M4TzgJRxgmyB6QEY.jpg'), publicId: null },
    youtubeId: 'COv52Qyctws',
    synopsis: 'A high-security prison warden orchestrates a series of crimes to bring attention to the corruption and injustice plaguing society.',
    cast: ['Shah Rukh Khan', 'Nayanthara', 'Vijay Sethupathi', 'Deepika Padukone'],
    director: 'Atlee',
    smartLabel: '🇮🇳 Blockbuster Revenge Saga',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'Kantara',
    year: 2022,
    rating: 8.4,
    duration: '2h 28m',
    genres: ['Action', 'Drama', 'Fantasy'],
    poster:   { url: p('/t11W932P0d4l726T967399aE5zB.jpg'), publicId: null },
    backdrop: { url: b('/7lI95hJ9n0WLIJdR7GNOhFdEpBi.jpg'), publicId: null },
    youtubeId: 'nuSMGtZhsAc',
    synopsis: 'A rebellious man becomes a protector of the forest and his community when an evil force threatens their land and ancient traditions.',
    cast: ['Rishab Shetty', 'Sapthami Gowda', 'Kishore', 'Achyuth Kumar'],
    director: 'Rishab Shetty',
    smartLabel: '🇮🇳 Cult Phenomenon',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'Kalki 2898 AD',
    year: 2024,
    rating: 6.8,
    duration: '3h 1m',
    genres: ['Sci-Fi', 'Action', 'Fantasy'],
    poster:   { url: p('/dBth71fJaXDSMrMgNXYSqIqAtji.jpg'), publicId: null },
    backdrop: { url: b('/5Um4XimHfHAaEHVbJpGLcJuO6mE.jpg'), publicId: null },
    youtubeId: 'kYJ4J4j8a-E',
    synopsis: 'Set in a futuristic dystopia, a bounty hunter fights for survival and unknowingly becomes entangled with an immortal protector guarding a woman who may hold the key to humanity\'s salvation.',
    cast: ['Prabhas', 'Deepika Padukone', 'Amitabh Bachchan', 'Kamal Haasan'],
    director: 'Nag Ashwin',
    smartLabel: '🇮🇳 India\'s Sci-Fi Epic',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: '3 Idiots',
    year: 2009,
    rating: 8.4,
    duration: '2h 50m',
    genres: ['Comedy', 'Drama'],
    poster:   { url: p('/wbE5SRTZFtQxgj2nIo4HJpQDk0k.jpg'), publicId: null },
    backdrop: { url: b('/yYi0SZrOHEpuKiF2sZL6xHhbEHR.jpg'), publicId: null },
    youtubeId: 'n9f02R7S-6s',
    synopsis: 'Two friends search for their long-lost companion. On the journey they remember their college days and how their friend changed their lives through his unorthodox views on education.',
    cast: ['Aamir Khan', 'R. Madhavan', 'Sharman Joshi', 'Kareena Kapoor'],
    director: 'Rajkumar Hirani',
    smartLabel: '🇮🇳 All-Time Comedy Classic',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'Vikram',
    year: 2022,
    rating: 8.4,
    duration: '2h 54m',
    genres: ['Action', 'Thriller', 'Crime'],
    poster:   { url: p('/x82R3Gx484F2L4JcQ3J77H9R1yY.jpg'), publicId: null },
    backdrop: { url: b('/cY68rLhz2j7EhqYFGhR7b4bHHnR.jpg'), publicId: null },
    youtubeId: 'J_5Wp16Y-58',
    synopsis: 'A special agent is tasked with tracking down a masked militant group that murders high-profile drug dealers. The investigation leads him to surprising connections.',
    cast: ['Kamal Haasan', 'Fahadh Faasil', 'Vijay Sethupathi', 'Suriya'],
    director: 'Lokesh Kanagaraj',
    smartLabel: '🇮🇳 Tamil Action Masterpiece',
  },
  {
    // INDIAN CINEMA 🇮🇳
    title: 'Salaar: Part 1 – Ceasefire',
    year: 2023,
    rating: 6.9,
    duration: '2h 59m',
    genres: ['Action', 'Drama', 'Thriller'],
    poster:   { url: p('/47Q5X5M45J4q5H5eQpWbXW48Qe2.jpg'), publicId: null },
    backdrop: { url: b('/nC5BoXLB5YNXMVcakb1Ynm8JNrr.jpg'), publicId: null },
    youtubeId: '4ZRyzacM-aU',
    synopsis: 'A gangster\'s promise to his dying friend leads him back to a violent kingdom to protect the son who is being targeted by a ruthless enemy.',
    cast: ['Prabhas', 'Prithviraj Sukumaran', 'Shruti Haasan', 'Jagapathi Babu'],
    director: 'Prashanth Neel',
    smartLabel: '🇮🇳 Pan-India Blockbuster',
  },
];

// ─── Seed Version ──────────────────────────────────────────────────────────────
export const CURRENT_SEED_VERSION = '2026-06-streamflix-v1';

// ─── Seed Function ─────────────────────────────────────────────────────────────
export async function seedMoviesProduction(options = {}) {
  const isDryRun = options.isDryRun ?? process.argv.includes('--dry-run');
  const shouldConnect = options.shouldConnect ?? false;

  try {
    if (shouldConnect) {
      const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/StreamFlix';
      await mongoose.connect(mongoUri);
      console.log('📦 Connected to MongoDB');
    }
    console.log(`🔧 Mode: ${isDryRun ? 'DRY RUN (no changes)' : 'LIVE UPSERT'}`);
    console.log(`📽️  Processing ${movieCatalog.length} movies...\n`);

    let inserted = 0;
    let updated = 0;
    let skipped = 0;
    const errors = [];

    for (const movie of movieCatalog) {
      try {
        if (isDryRun) {
          const existing = await Movie.findOne({ title: movie.title, year: movie.year });
          if (existing) {
            console.log(`  ⏭  SKIP  "${movie.title}" (${movie.year}) — exists`);
            skipped++;
          } else {
            console.log(`  ➕ INSERT "${movie.title}" (${movie.year}) — would insert`);
            inserted++;
          }
          continue;
        }

        const result = await Movie.findOneAndUpdate(
          { title: movie.title, year: movie.year },
          {
            $set: {
              rating: movie.rating,
              duration: movie.duration,
              genres: movie.genres,
              poster: movie.poster,
              backdrop: movie.backdrop,
              youtubeId: movie.youtubeId,
              synopsis: movie.synopsis,
              cast: movie.cast,
              director: movie.director,
              smartLabel: movie.smartLabel,
            },
          },
          {
            upsert: true,
            new: true,
            setDefaultsOnInsert: true,
          }
        );

        if (result.createdAt.getTime() === result.updatedAt.getTime()) {
          // Newly inserted
          console.log(`  ✅ INSERTED "${movie.title}" (${movie.year})`);
          inserted++;
        } else {
          console.log(`  🔄 UPDATED  "${movie.title}" (${movie.year})`);
          updated++;
        }
      } catch (err) {
        console.error(`  ❌ ERROR    "${movie.title}" (${movie.year}): ${err.message}`);
        errors.push({ title: movie.title, year: movie.year, error: err.message });
      }
    }

    console.log('\n' + '═'.repeat(55));
    console.log('📊 SEED SUMMARY');
    console.log('═'.repeat(55));
    console.log(`  ✅ Inserted : ${inserted}`);
    console.log(`  🔄 Updated  : ${updated}`);
    console.log(`  ⏭  Skipped  : ${skipped}`);
    console.log(`  ❌ Errors   : ${errors.length}`);
    if (errors.length > 0) {
      console.log('\n  Error details:');
      errors.forEach(e => console.log(`    - ${e.title} (${e.year}): ${e.error}`));
    }
    console.log('═'.repeat(55));
    console.log('✅ Users, reviews, watchlists and admins were NOT touched.\n');

    if (shouldConnect) {
      await mongoose.disconnect();
    }
    return { inserted, updated, skipped, errorCount: errors.length };
  } catch (err) {
    console.error('❌ Fatal error:', err);
    if (shouldConnect) {
      try { await mongoose.disconnect(); } catch (_) {}
    }
    throw err;
  }
}

import { fileURLToPath } from 'url';
const isMain = process.argv[1] && (
  process.argv[1] === fileURLToPath(import.meta.url) ||
  process.argv[1].endsWith('seedMoviesProduction.js')
);

if (isMain) {
  (async () => {
    try {
      const stats = await seedMoviesProduction({ shouldConnect: true });
      process.exit(stats.errorCount > 0 ? 1 : 0);
    } catch (err) {
      process.exit(1);
    }
  })();
}
