/**
 * Post-Generation Grounding and Anti-Hallucination Validator (R2)
 *
 * Verifies that candidate explanations generated by Gemini strictly adhere to
 * authoritative backend evidence and structural constraints.
 *
 * Checks:
 * 1. Zero Score Leakage: Detects and rejects any internal continuous scores or raw weights.
 * 2. Grounding & Anti-Hallucination: Detects fabricated awards, box office claims, actors, or directors.
 * 3. Controlled Chip Vocabulary: Enforces that evidence chips are a strict subset of controlledChipVocabulary.
 * 4. Chip Count: Enforces maximum of 3 chips.
 * 5. Reason Sentence Count: Enforces maximum of 1-2 sentences.
 */

// Forbidden fabricated award / commercial buzzwords unless backed by explicit metadata
const FABRICATED_AWARD_PATTERNS = [
  /\boscar(?:s|\s+winner|\s+winning|\s+nominated)?\b/i,
  /\bacademy\s+award(?:s)?\b/i,
  /\bgolden\s+globe(?:s)?\b/i,
  /\bnational\s+(?:film\s+)?award(?:s)?\b/i,
  /\bbafta\b/i,
  /\bpalme\s+d'or\b/i,
  /\bgrammy\b/i,
  /\bemmy\b/i,
  /\bhighest\s+grossing\b/i,
  /\bbox\s+office\s+(?:smash|hit|record)\b/i,
  /\bblockbuster\s+hit\b/i,
];

// Internal score leakage detection patterns
const SCORE_LEAKAGE_PATTERNS = [
  /\b(?:semantic|hybrid|behavior|metadata|quality|novelty|mmr)\s*score\b/i,
  /\bscore\s*:\s*0\.\d+\b/i,
  /\bweight\s*:\s*0\.\d+\b/i,
  /\b(?:0\.\d{2,4})\s*(?:relevance|similarity|confidence)\b/i,
];

/**
 * Splits text into individual sentences.
 */
export function countSentences(text) {
  if (!text || typeof text !== 'string') return 0;
  const cleaned = text.trim();
  if (!cleaned) return 0;
  const matches = cleaned.match(/[^.!?]+(?:[.!?]+|$)/g);
  return matches ? matches.map(s => s.trim()).filter(Boolean).length : 1;
}

/**
 * Truncates text to at most maxSentences.
 */
export function truncateToSentences(text, maxSentences = 2) {
  if (!text || typeof text !== 'string') return '';
  const cleaned = text.trim();
  const sentences = cleaned.match(/[^.!?]+(?:[.!?]+|$)/g);
  if (!sentences || sentences.length <= maxSentences) return cleaned;
  return sentences.slice(0, maxSentences).map(s => s.trim()).join(' ');
}

/**
 * Validates and sanitizes a generated explanation against authoritative evidence.
 *
 * @param {Object} candidate - LLM response ({ headline, reason, evidence, confidence })
 * @param {Object} evidence - Backend Evidence Object
 * @param {Object} [movieDoc] - Movie metadata object (optional, for cast/director verification)
 * @returns {{
 *   isValid: boolean,
 *   sanitized: Object|null,
 *   violations: string[],
 *   isHallucination: boolean,
 *   hasScoreLeakage: boolean
 * }}
 */
export function validateExplanation(candidate, evidence = {}, movieDoc = null) {
  const violations = [];
  let isHallucination = false;
  let hasScoreLeakage = false;

  if (!candidate || typeof candidate !== 'object') {
    return {
      isValid: false,
      sanitized: null,
      violations: ['Candidate explanation is not a valid object'],
      isHallucination: false,
      hasScoreLeakage: false,
    };
  }

  // 1. Headline Validation
  let headline = String(candidate.headline || '').trim();
  if (!headline) {
    violations.push('Missing or empty headline');
  } else if (headline.length > 120) {
    headline = headline.slice(0, 117) + '...';
  }

  // 2. Reason Validation & Sentence Count
  let reason = String(candidate.reason || '').trim();
  if (!reason) {
    violations.push('Missing or empty reason');
  }

  const numSentences = countSentences(reason);
  if (numSentences > 2) {
    // Truncate to 2 sentences cleanly
    reason = truncateToSentences(reason, 2);
  }

  // 3. Score Leakage Check
  const fullText = `${headline} ${reason}`;
  for (const pattern of SCORE_LEAKAGE_PATTERNS) {
    if (pattern.test(fullText)) {
      violations.push(`Internal score leaked in explanation: pattern ${pattern}`);
      hasScoreLeakage = true;
      break;
    }
  }

  // 4. Hallucination: Fabricated Awards & Commercial Buzzwords
  for (const pattern of FABRICATED_AWARD_PATTERNS) {
    if (pattern.test(fullText)) {
      // Check if the movie synopsis actually mentions this (unlikely, but check)
      const inSynopsis = movieDoc?.synopsis && pattern.test(movieDoc.synopsis);
      if (!inSynopsis) {
        violations.push(`Fabricated award or commercial claim detected: ${pattern}`);
        isHallucination = true;
        break;
      }
    }
  }

  // 5. Hallucination: Fabricated Actors or Directors
  const knownCast = new Set([
    ...(movieDoc?.cast || []).map(c => String(c).toLowerCase().trim()),
    ...(evidence?.matchedActors || []).map(a => String(a).toLowerCase().trim()),
  ]);
  const knownDirector = (movieDoc?.director || evidence?.matchedDirector || '').toLowerCase().trim();

  // Regex pattern to spot "starring <Name>" or "featuring <Name>"
  const starringMatch = reason.match(/(?:starring|featuring)\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)/);
  if (starringMatch && starringMatch[1]) {
    const actorClaim = starringMatch[1].toLowerCase().trim();
    const isKnownActor = Array.from(knownCast).some(a => a.includes(actorClaim) || actorClaim.includes(a));
    if (!isKnownActor) {
      violations.push(`Fabricated actor claim detected: "${starringMatch[1]}"`);
      isHallucination = true;
    }
  }

  const directorMatch = reason.match(/(?:directed by|from director)\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)/);
  if (directorMatch && directorMatch[1]) {
    const dirClaim = directorMatch[1].toLowerCase().trim();
    const isKnownDirector = knownDirector && (knownDirector.includes(dirClaim) || dirClaim.includes(knownDirector));
    if (!isKnownDirector) {
      violations.push(`Fabricated director claim detected: "${directorMatch[1]}"`);
      isHallucination = true;
    }
  }

  // 6. Controlled Chip Vocabulary Validation
  const vocabulary = new Set(
    (evidence.controlledChipVocabulary || []).map(c => String(c).toLowerCase().trim())
  );

  const rawChips = Array.isArray(candidate.evidence) ? candidate.evidence : [];
  const validChips = [];

  for (const chip of rawChips) {
    if (!chip || typeof chip !== 'string') continue;
    const cleanChip = chip.trim();
    const cleanLower = cleanChip.toLowerCase();

    // Check if chip matches any item in vocabulary (exact or case-insensitive)
    const matchedVocab = (evidence.controlledChipVocabulary || []).find(
      v => v.toLowerCase().trim() === cleanLower
    );

    if (matchedVocab) {
      if (!validChips.includes(matchedVocab)) {
        validChips.push(matchedVocab);
      }
    } else {
      violations.push(`Invented chip "${cleanChip}" not present in controlledChipVocabulary`);
    }
  }

  // If no valid chips were retained, pick up to 3 from controlledChipVocabulary
  let finalChips = validChips.slice(0, 3);
  if (finalChips.length === 0 && (evidence.controlledChipVocabulary || []).length > 0) {
    finalChips = evidence.controlledChipVocabulary.slice(0, 3);
  }

  // 7. Confidence Validation
  const validConfidences = ['high', 'medium', 'low'];
  const confidence = validConfidences.includes(candidate.confidence) ? candidate.confidence : 'medium';

  // Overall validity: If critical hallucination or score leakage is detected, reject completely!
  const isValid = !isHallucination && !hasScoreLeakage && Boolean(headline) && Boolean(reason);

  return {
    isValid,
    isHallucination,
    hasScoreLeakage,
    violations,
    sanitized: isValid
      ? {
          headline,
          reason,
          evidence: finalChips,
          confidence,
        }
      : null,
  };
}
